begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
do $$declare n integer; a uuid; begin for n in 1..8 loop
 a:=('53000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid;
 insert into auth.users(id,email,email_confirmed_at) values(a,'batch-'||n||'@example.test',now());
 perform public.provision_member(a,'Fictif-'||lpad(n::text,2,'0'),'Présence');
 end loop;end$$;
update public.members set role='admin' where email='batch-8@example.test';
create temp table people as select id,split_part(split_part(email,'@',1),'-',2)::integer n from public.members where email like 'batch-%@example.test';
create temp table scenarios(label text,id uuid,preview jsonb,audit_count bigint);
grant select on people to authenticated; grant select,insert,update on scenarios to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','53000000-0000-4000-8000-000000000008',true);
insert into scenarios(label,id) values
('lot',public.save_session('2025-10-01','21:00','22:00','Lot fictif','','','',5,true,false,false)),
('future',public.save_session('2030-10-01','21:00','22:00','Future','','','',5,true,false,false)),
('withdraw',public.save_session('2025-10-02','21:00','22:00','Désistement','','','',2,true,false,false));
select public.set_session_rsvp((select id from scenarios where label='lot'),'yes',id) from people where n<=5 or n=7;
select public.set_draft_selection((select id from scenarios where label='lot'),id,'selected') from people where n<=5;
select public.publish_selection((select id from scenarios where label='lot'));
select public.set_attendance((select id from scenarios where label='lot'),(select id from people where n=2),'absent');
select public.set_attendance((select id from scenarios where label='lot'),(select id from people where n=3),'not_dived');
select public.set_attendance((select id from scenarios where label='lot'),(select id from people where n=4),'dived');
select public.set_attendance((select id from scenarios where label='lot'),(select id from people where n=6),'dived');
-- The private draft intentionally differs from the effective publication.
select public.set_draft_selection((select id from scenarios where label='lot'),(select id from people where n=1),'waiting');
select public.set_draft_selection((select id from scenarios where label='lot'),(select id from people where n=7),'selected');
update scenarios set audit_count=(select count(*) from public.audit_events where session_id=scenarios.id),preview=public.get_attendance_batch_preview(id) where label='lot';
select is((select preview->>'member_count' from scenarios where label='lot'),'2','Only two unknown effectively published confirmations are proposed');
select is((select jsonb_agg(r->>'first_name' order by r->>'first_name') from jsonb_array_elements((select preview->'rows' from scenarios where label='lot')) r),'["Fictif-01", "Fictif-05"]'::jsonb,'Preview names concern publication, not private draft or waiting/replacement');
select is((select count(*) from public.audit_events where session_id=(select id from scenarios where label='lot')),(select audit_count from scenarios where label='lot'),'Preview performs no audited writes');
select is((select completed_count from public.get_season_counts(2025) where member_id=(select id from people where n=1)),0::bigint,'No seasonal count before closure');
select throws_ok($$select public.get_attendance_batch_preview((select id from scenarios where label='future'))$$,'22023',null,'No preview before Paris session end');
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='future'),'anything')$$,'22023',null,'No batch before session end');
select set_config('request.jwt.claim.sub','53000000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.get_attendance_batch_preview((select id from scenarios where label='lot'))$$,'42501',null,'Member cannot read nominal admin preview');
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='lot'),(select preview->>'fingerprint' from scenarios where label='lot'))$$,'42501',null,'Member cannot apply batch');
select set_config('request.jwt.claim.sub','53000000-0000-4000-8000-000000000008',true);
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='lot'),null)$$,'40001','ATTENDANCE_PREVIEW_STALE','Explicit current fingerprint required');
select public.set_attendance((select id from scenarios where label='lot'),(select id from people where n=5),'absent');
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='lot'),(select preview->>'fingerprint' from scenarios where label='lot'))$$,'40001','ATTENDANCE_PREVIEW_STALE','Concurrent attendance change refuses the entire batch');
select is((select attendance_status::text from public.session_participations where session_id=(select id from scenarios where label='lot') and member_id=(select id from people where n=1)),'unknown','Stale batch never updates another member');
select public.set_attendance((select id from scenarios where label='lot'),(select id from people where n=5),'unknown');
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='lot'),(select preview->>'fingerprint' from scenarios where label='lot'))$$,'40001','ATTENDANCE_PREVIEW_STALE','ABA attendance correction still requires reconfirmation');
update scenarios set preview=public.get_attendance_batch_preview(id),audit_count=(select count(*) from public.audit_events where session_id=scenarios.id) where label='lot';
reset role;
create function pg_temp.reject_batch_audit() returns trigger language plpgsql as $$begin if new.event_type='attendance_changed' and new.target_member_id=(select id from people where n=5) then raise exception 'Injected batch audit failure'; end if; return new;end$$;
create trigger inject_batch_failure before insert on public.audit_events for each row execute function pg_temp.reject_batch_audit();
set local role authenticated;
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='lot'),(select preview->>'fingerprint' from scenarios where label='lot'))$$,'P0001','Injected batch audit failure','Later audit failure rolls back the whole lot');
select is((select count(*) from public.session_participations where session_id=(select id from scenarios where label='lot') and member_id in(select id from people where n in(1,5)) and attendance_status='unknown'),2::bigint,'All proposed attendance remains unknown after rollback');
select is((select count(*) from public.audit_events where session_id=(select id from scenarios where label='lot')),(select audit_count from scenarios where label='lot'),'Rollback also removes earlier per-member audit');
reset role;drop trigger inject_batch_failure on public.audit_events;set local role authenticated;
select is(public.mark_confirmed_attendance((select id from scenarios where label='lot'),(select preview->>'fingerprint' from scenarios where label='lot')),2,'Fresh batch updates exactly the two proposed members');
select is((select attendance_status::text from public.session_participations where session_id=(select id from scenarios where label='lot') and member_id=(select id from people where n=2)),'absent','Existing absent is preserved');
select is((select attendance_status::text from public.session_participations where session_id=(select id from scenarios where label='lot') and member_id=(select id from people where n=3)),'not_dived','Existing not-dived is preserved');
select is((select count(*) from public.session_participations where session_id=(select id from scenarios where label='lot') and attendance_status='dived'),4::bigint,'Existing dives and out-of-selection replacement are preserved');
select is((select attendance_status::text from public.session_participations where session_id=(select id from scenarios where label='lot') and member_id=(select id from people where n=7)),'unknown','Waiting/draft-only member is untouched');
select is((select status::text from public.sessions where id=(select id from scenarios where label='lot')),'open','Batch never closes the bilan');
select is((select completed_count from public.get_season_counts(2025) where member_id=(select id from people where n=1)),0::bigint,'Batch alone does not affect seasonal count');
select is((select count(*) from public.audit_events where session_id=(select id from scenarios where label='lot')),(select audit_count+2 from scenarios where label='lot'),'Every applied attendance uses existing per-member audit');
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='lot'),(select preview->>'fingerprint' from scenarios where label='lot'))$$,'40001','ATTENDANCE_PREVIEW_STALE','Double apply is rejected');
update scenarios set preview=public.get_attendance_batch_preview(id),audit_count=(select count(*) from public.audit_events where session_id=scenarios.id) where label='lot';
select is(public.mark_confirmed_attendance((select id from scenarios where label='lot'),(select preview->>'fingerprint' from scenarios where label='lot')),0,'Fresh empty rerun is a safe no-op');
select is((select count(*) from public.audit_events where session_id=(select id from scenarios where label='lot')),(select audit_count from scenarios where label='lot'),'Empty rerun creates no audit');
select public.close_session_bilan((select id from scenarios where label='lot'));
select is((select completed_count from public.get_season_counts(2025) where member_id=(select id from people where n=1)),1::bigint,'Only explicit closure increments season');
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='lot'),(select preview->>'fingerprint' from scenarios where label='lot'))$$,'22023',null,'Closed bilan rejects batch');
select public.reopen_session_bilan((select id from scenarios where label='lot'));
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='lot'),(select preview->>'fingerprint' from scenarios where label='lot'))$$,'40001','ATTENDANCE_PREVIEW_STALE','Close/reopen invalidates a previous preview');
select public.set_session_rsvp((select id from scenarios where label='withdraw'),'yes',id) from people where n in(1,5);
select public.set_draft_selection((select id from scenarios where label='withdraw'),id,'selected') from people where n in(1,5);
select public.publish_selection((select id from scenarios where label='withdraw'));
update scenarios set preview=public.get_attendance_batch_preview(id) where label='withdraw';
select public.set_session_rsvp((select id from scenarios where label='withdraw'),'no',(select id from people where n=5),false,true);
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='withdraw'),(select preview->>'fingerprint' from scenarios where label='withdraw'))$$,'40001','ATTENDANCE_PREVIEW_STALE','Withdrawal invalidates preview');
update scenarios set preview=public.get_attendance_batch_preview(id) where label='withdraw';
select is((select preview->>'member_count' from scenarios where label='withdraw'),'1','New preview excludes effective withdrawal');
select public.publish_selection((select id from scenarios where label='withdraw'));
select throws_ok($$select public.mark_confirmed_attendance((select id from scenarios where label='withdraw'),(select preview->>'fingerprint' from scenarios where label='withdraw'))$$,'40001','ATTENDANCE_PREVIEW_STALE','Republication requires a fresh preview');
-- Boundary counters use the existing closed attendance model, never selection.
insert into scenarios(label,id) values
('august',public.save_session('2025-08-31','21:00','22:00','Août','','','',1,true,false,false)),
('september',public.save_session('2025-09-01','21:00','22:00','Septembre','','','',1,true,false,false));
select public.set_session_rsvp(id,'yes',(select id from people where n=1)) from scenarios where label in('august','september');
select public.set_draft_selection(id,(select id from people where n=1),'selected') from scenarios where label in('august','september');
select public.publish_selection(id) from scenarios where label in('august','september');
update scenarios set preview=public.get_attendance_batch_preview(id) where label in('august','september');
select public.mark_confirmed_attendance(id,preview->>'fingerprint') from scenarios where label in('august','september');
select public.close_session_bilan(id) from scenarios where label in('august','september');
select is((select completed_count from public.get_season_counts(2024) where member_id=(select id from people where n=1)),1::bigint,'August batch is counted in preceding season');
select is((select completed_count from public.get_season_counts(2025) where member_id=(select id from people where n=1)),1::bigint,'September batch counted in new season; reopened lot excluded');
reset role;set local role anon;
select throws_ok($$select public.get_attendance_batch_preview('53000000-0000-4000-8000-000000000001')$$,'42501',null,'Anonymous cannot read preview');
select throws_ok($$select public.mark_confirmed_attendance('53000000-0000-4000-8000-000000000001','x')$$,'42501',null,'Anonymous cannot apply batch');
reset role;set local role service_role;
select throws_ok($$select public.mark_confirmed_attendance('53000000-0000-4000-8000-000000000001','x')$$,'42501',null,'Service role has no browser batch grant');
reset role;select * from finish();rollback;
