begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('60000000-0000-4000-8000-000000000001','attendance.member@example.test',now()),
('60000000-0000-4000-8000-000000000002','attendance.admin@example.test',now());
select public.provision_member('60000000-0000-4000-8000-000000000001','Membre','Présence');
select public.provision_member('60000000-0000-4000-8000-000000000002','Admin','Présence');
update public.members set role='admin' where email='attendance.admin@example.test';
create temp table attendance_members as select id,email from public.members where email like 'attendance.%';
create temp table attendance_sessions(label text,id uuid);
grant select on attendance_members to authenticated;
grant select,insert on attendance_sessions to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','60000000-0000-4000-8000-000000000002',true);
insert into attendance_sessions values
('before',public.save_session('2025-08-31','21:00','22:00','Avant septembre','','','',1,true,false,false)),
('start',public.save_session('2025-09-01','21:00','22:00','Septembre','','','',1,true,false,false)),
('end',public.save_session('2026-08-31','21:00','22:00','Août','','','',1,true,false,false)),
('after',public.save_session('2026-09-01','21:00','22:00','Septembre suivant','','','',1,true,false,false)),
('future',public.save_session('2030-10-01','21:00','22:00','Future','','','',1,true,false,false));
select public.set_session_rsvp((select id from attendance_sessions where label='start'),'yes',(select id from attendance_members where email='attendance.member@example.test'));
select public.set_draft_selection((select id from attendance_sessions where label='start'),(select id from attendance_members where email='attendance.member@example.test'),'selected');
select public.publish_selection((select id from attendance_sessions where label='start'));
select is((select completed_count from public.get_season_counts(2025) where member_id=(select id from attendance_members where email='attendance.member@example.test')),0::bigint,'Selection alone never counts');
select throws_ok($$select public.close_session_bilan((select id from attendance_sessions where label='start'))$$,'22023',null,'Every effective selected attendance must be known before closure');
select throws_ok($$select public.set_attendance((select id from attendance_sessions where label='future'),public.current_member_id(),'dived')$$,'22023',null,'Future attendance cannot be recorded');
select throws_ok($$select public.close_session_bilan((select id from attendance_sessions where label='future'))$$,'22023',null,'Future session cannot be closed');
select public.set_attendance(id,(select id from attendance_members where email='attendance.member@example.test'),'dived') from attendance_sessions where label<>'future';
select is((select completed_count from public.get_season_counts(2025) where member_id=(select id from attendance_members where email='attendance.member@example.test')),0::bigint,'Unclosed actual attendance does not count yet');
select public.set_attendance((select id from attendance_sessions where label='start'),public.current_member_id(),'dived');
select throws_ok($$select public.close_session_bilan((select id from attendance_sessions where label='start'))$$,'22023',null,'Bilan cannot validate more divers than capacity');
select public.set_attendance((select id from attendance_sessions where label='start'),public.current_member_id(),'not_dived');
select set_config('request.jwt.claim.sub','60000000-0000-4000-8000-000000000001',true);
select is((select count(*) from public.get_session_attendance((select id from attendance_sessions where label='start'))),1::bigint,'Unfinished attendance of others is private');
select throws_ok($$select public.get_bilan_state((select id from attendance_sessions where label='start'))$$,'42501',null,'Member cannot read private bilan administration state');
select set_config('request.jwt.claim.sub','60000000-0000-4000-8000-000000000002',true);
select public.set_draft_selection((select id from attendance_sessions where label='start'),(select id from attendance_members where email='attendance.member@example.test'),'waiting');
reset role;
create function pg_temp.reject_bilan_audit() returns trigger language plpgsql as $$begin if new.event_type='bilan_closed' then raise exception 'Injected bilan audit failure'; end if; return new; end;$$;
create trigger inject_bilan_failure before insert on public.audit_events for each row execute function pg_temp.reject_bilan_audit();
set local role authenticated;
select throws_ok($$select public.close_session_bilan((select id from attendance_sessions where label='start'))$$,'P0001','Injected bilan audit failure','Audit failure rolls back entire closure');
select is((select status::text from public.sessions where id=(select id from attendance_sessions where label='start')),'open','Failed closure leaves session open');
select is((select count(*) from public.selection_drafts where session_id=(select id from attendance_sessions where label='start')),1::bigint,'Failed closure preserves private draft');
reset role;
drop trigger inject_bilan_failure on public.audit_events;
set local role authenticated;
select lives_ok($$select public.close_session_bilan((select id from attendance_sessions where label='start'))$$,'Admin closes validated bilan');
select public.close_session_bilan(id) from attendance_sessions where label in('before','end','after');
select is((select completed_count from public.get_season_counts(2024) where member_id=(select id from attendance_members where email='attendance.member@example.test')),1::bigint,'August 31 belongs to preceding season');
select is((select completed_count from public.get_season_counts(2025) where member_id=(select id from attendance_members where email='attendance.member@example.test')),2::bigint,'September 1 through August 31 are included');
select is((select completed_count from public.get_season_counts(2026) where member_id=(select id from attendance_members where email='attendance.member@example.test')),1::bigint,'Following September belongs to next season');
select is((select completed_count from public.get_season_counts(2025) where member_id=public.current_member_id()),0::bigint,'Not-dived never counts');
select is((select rsvp::text from public.session_participations where session_id=(select id from attendance_sessions where label='end') and member_id=(select id from attendance_members where email='attendance.member@example.test')),'unanswered','Real replacement attendance does not invent an RSVP');
select is((select registration_open from public.sessions where id=(select id from attendance_sessions where label='start')),false,'Closure closes registration');
select is((select count(*) from public.selection_drafts where session_id=(select id from attendance_sessions where label='start')),0::bigint,'Closure abandons selection draft');
select throws_ok($$select public.set_attendance((select id from attendance_sessions where label='start'),public.current_member_id(),'dived')$$,'22023',null,'Closed bilan must be reopened before correction');
select public.close_session_bilan((select id from attendance_sessions where label='start'));
select is((select count(*) from public.audit_events where session_id=(select id from attendance_sessions where label='start') and event_type='bilan_closed'),1::bigint,'Idempotent closure creates one audit');
select lives_ok($$select public.reopen_session_bilan((select id from attendance_sessions where label='start'))$$,'Admin reopens for correction');
select is((select registration_open from public.sessions where id=(select id from attendance_sessions where label='start')),false,'Reopening does not reopen registration');
select is((select attendance_status::text from public.session_participations where session_id=(select id from attendance_sessions where label='start') and member_id=(select id from attendance_members where email='attendance.member@example.test')),'dived','Reopening preserves existing attendance');
select is((select completed_count from public.get_season_counts(2025) where member_id=(select id from attendance_members where email='attendance.member@example.test')),1::bigint,'Reopening immediately removes that session from count');
select public.set_payment_status((select id from attendance_sessions where label='start'),(select id from attendance_members where email='attendance.member@example.test'),'paid');
select public.set_attendance((select id from attendance_sessions where label='start'),(select id from attendance_members where email='attendance.member@example.test'),'absent');
select public.close_session_bilan((select id from attendance_sessions where label='start'));
select is((select completed_count from public.get_season_counts(2025) where member_id=(select id from attendance_members where email='attendance.member@example.test')),1::bigint,'Corrected absent does not count after reclosure');
select is((select payment_status::text from public.session_participations where session_id=(select id from attendance_sessions where label='start') and member_id=(select id from attendance_members where email='attendance.member@example.test')),'paid','Attendance preserves payment');
select set_config('request.jwt.claim.sub','60000000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.set_attendance((select id from attendance_sessions where label='end'),public.current_member_id(),'dived')$$,'42501',null,'Member cannot edit attendance');
select throws_ok($$select public.close_session_bilan((select id from attendance_sessions where label='end'))$$,'42501',null,'Member cannot close bilan');
select throws_ok($$select public.reopen_session_bilan((select id from attendance_sessions where label='end'))$$,'42501',null,'Member cannot reopen bilan');
select throws_ok($$update public.session_participations set attendance_status='dived'$$,'42501',null,'Direct browser attendance writes forbidden');
select throws_ok($$select payment_status from public.get_session_attendance((select id from attendance_sessions where label='end'))$$,'42703',null,'Attendance projection reveals no payment');
select is((select attendance_status::text from public.get_session_attendance((select id from attendance_sessions where label='start')) where member_id=public.current_member_id()),'absent','Member sees validated history');
select is((select completed_count from public.get_season_counts(2025) where member_id=public.current_member_id()),1::bigint,'Member sees derived season count');
select is((select count(*) from public.get_season_counts(2025)),1::bigint,'Season counts cannot expose the member directory to a regular member');
select throws_ok($$select public.get_season_counts(10000)$$,'22023',null,'Invalid season is rejected');
select throws_ok($$select public.session_has_ended('2026-01-01','22:00')$$,'42501',null,'Private time helper is not a browser RPC');
reset role;
select ok(public.session_has_ended(((statement_timestamp() at time zone 'Europe/Paris')-interval '1 minute')::date,((statement_timestamp() at time zone 'Europe/Paris')-interval '1 minute')::time),'Recent Paris local end is past');
select ok(not public.session_has_ended(((statement_timestamp() at time zone 'Europe/Paris')+interval '1 minute')::date,((statement_timestamp() at time zone 'Europe/Paris')+interval '1 minute')::time),'Upcoming Paris local end is future');
set local role anon;
select throws_ok($$select public.get_season_counts(2025)$$,'42501',null,'Anonymous cannot read season counts');
select throws_ok($$select public.set_attendance('00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000001','dived')$$,'42501',null,'Anonymous cannot write attendance');
reset role;
select * from finish();
rollback;
