begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('90000000-0000-4000-8000-000000000001','carreview.driver@example.test',now()),
('90000000-0000-4000-8000-000000000002','carreview.passenger@example.test',now());
select public.provision_member('90000000-0000-4000-8000-000000000001','Conducteur','Voiture');
select public.provision_member('90000000-0000-4000-8000-000000000002','Passager','Voiture');
update public.members set role='admin',phone='0612345678',current_level='MF1',caci_expiry_date='2030-12-31' where email='carreview.driver@example.test';
update public.members set caci_expiry_date='2030-12-31' where email='carreview.passenger@example.test';
create temp table carreview_members as select id,email from public.members where email like 'carreview.%';
create temp table carreview_sessions(id uuid,label text);
grant select on carreview_members to authenticated;
grant select,insert on carreview_sessions to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','90000000-0000-4000-8000-000000000001',true);
insert into carreview_sessions select public.save_session('2030-10-01','21:00','22:00','Voiture','','','',2,true,false,false),'main';
insert into carreview_sessions select public.save_session('2030-11-01','21:00','22:00','Autre voiture','','','',2,true,false,false),'other';
select public.set_session_rsvp((select id from carreview_sessions where label='main'),'yes',id) from carreview_members;
select public.set_draft_selection((select id from carreview_sessions where label='main'),(select id from carreview_members where email='carreview.passenger@example.test'),'selected');
select public.publish_selection((select id from carreview_sessions where label='main'));
select public.set_payment_status((select id from carreview_sessions where label='main'),(select id from carreview_members where email='carreview.passenger@example.test'),'paid');
select public.offer_car((select id from carreview_sessions where label='main'),1,'Parking provisoire','');
select is((select has_usual_car from public.members where id=public.current_member_id()),false,'One-off offer never silently saves defaults');
select set_config('request.jwt.claim.sub','90000000-0000-4000-8000-000000000002',true);
select lives_ok($$select public.join_car((select id from carreview_sessions where label='main'),(select id from public.car_offers where session_id=(select id from carreview_sessions where label='main')))$$,'Booking with a waiting driver remains allowed');
select set_config('request.jwt.claim.sub','90000000-0000-4000-8000-000000000001',true);
select ok((select selection_ready and caci_ready and payment_ready and not transport_ready from public.get_admin_readiness((select id from carreview_sessions where label='main')) where member_id=(select id from carreview_members where email='carreview.passenger@example.test')),'Waiting-driver passenger is not falsely fully ready');
select ok((select transport_provisional and selection_basis='published' from public.get_admin_readiness((select id from carreview_sessions where label='main')) where member_id=(select id from carreview_members where email='carreview.passenger@example.test')),'Published basis explicitly marks provisional trip');
select public.set_draft_selection((select id from carreview_sessions where label='main'),public.current_member_id(),'selected');
select ok((select transport_ready and not transport_provisional and selection_basis='draft' from public.get_admin_readiness((select id from carreview_sessions where label='main')) where member_id=(select id from carreview_members where email='carreview.passenger@example.test')),'Private checklist uses driver from the same draft basis');
select is((select state from public.get_current_selection((select id from carreview_sessions where label='main')) where member_id=public.current_member_id()),'waiting','Draft readiness does not publish driver confirmation');
select public.publish_selection((select id from carreview_sessions where label='main'));
select ok((select transport_ready and not transport_provisional and selection_basis='published' from public.get_admin_readiness((select id from carreview_sessions where label='main')) where member_id=(select id from carreview_members where email='carreview.passenger@example.test')),'Driver publication resolves provisional trip');
select lives_ok($$select public.save_own_car_defaults(2,'Habitudes')$$,'Explicit opt-in saves only own convenience fields');
select ok((select has_usual_car and usual_passenger_seats=2 and usual_meeting_point='Habitudes' and phone='0612345678' and current_level='MF1' and role='admin' and caci_expiry_date='2030-12-31' from public.members where id=public.current_member_id()),'Opt-in preserves unrelated profile and privilege fields');
select is((select passenger_capacity from public.car_offers where session_id=(select id from carreview_sessions where label='main')),1,'Defaults never rewrite the current session offer');
select is((select count(*) from public.car_offers where session_id=(select id from carreview_sessions where label='other')),0::bigint,'Defaults never create future session offers');
select throws_ok($$select public.save_own_car_defaults(0,'')$$,'22023',null,'Defaults retain passenger seat bounds');
select throws_ok($$select public.save_own_car_defaults(2,repeat('x',201))$$,'22023',null,'Defaults retain meeting point bounds');
select public.set_draft_selection((select id from carreview_sessions where label='main'),public.current_member_id(),'declined');
select ok((select not transport_ready and transport_provisional and selection_basis='draft' from public.get_admin_readiness((select id from carreview_sessions where label='main')) where member_id=(select id from carreview_members where email='carreview.passenger@example.test')),'Declining driver in work draft changes draft checklist immediately');
select is((select count(*) from public.car_offers where session_id=(select id from carreview_sessions where label='main')),1::bigint,'Private exclusion keeps published car until publication');
select public.publish_selection((select id from carreview_sessions where label='main'));
select is((select count(*) from public.car_offers where session_id=(select id from carreview_sessions where label='main')),0::bigint,'Published exclusion removes driver offer');
select ok((select rsvp='yes' and transport_mode='needs' from public.session_participations where session_id=(select id from carreview_sessions where label='main') and member_id=(select id from carreview_members where email='carreview.passenger@example.test')),'Exclusion leaves passenger registered but unresolved');
select set_config('request.jwt.claim.sub','90000000-0000-4000-8000-000000000002',true);
select lives_ok($$select public.save_own_car_defaults(1,'Ponctuel')$$,'Regular member can opt in to own defaults');
select throws_ok($$select public.get_admin_readiness((select id from carreview_sessions where label='main'))$$,'42501',null,'Provisional readiness remains administrator-only');
reset role;
set local role anon;
select throws_ok($$select public.save_own_car_defaults(1,'')$$,'42501',null,'Anonymous defaults update denied');
reset role;
select * from finish();
rollback;
