begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('40000000-0000-4000-8000-000000000001','car.admin@example.test',now()),
('40000000-0000-4000-8000-000000000002','car.driver@example.test',now()),
('40000000-0000-4000-8000-000000000003','car.passenger@example.test',now()),
('40000000-0000-4000-8000-000000000004','car.other@example.test',now());
select public.provision_member('40000000-0000-4000-8000-000000000001','Admin','Voiture');
select public.provision_member('40000000-0000-4000-8000-000000000002','Conducteur','Voiture');
select public.provision_member('40000000-0000-4000-8000-000000000003','Passager','Voiture');
select public.provision_member('40000000-0000-4000-8000-000000000004','Autre','Voiture');
update public.members set role='admin' where email='car.admin@example.test';
create temp table members_fixture as select id,email from public.members where email like 'car.%';
create temp table sessions_fixture(id uuid);
create temp table cars_fixture(name text,id uuid);
create temp table second_session_fixture(id uuid);
grant select on members_fixture to authenticated;
grant select,insert on sessions_fixture,cars_fixture,second_session_fixture to authenticated;
set local role anon;
select throws_ok($$select * from public.car_offers$$,'42501',null,'Anonymous users cannot read car offers');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000001',true);
insert into sessions_fixture select public.save_session('2030-10-01','21:00','22:00','Voitures','','','',20,true,false,false);
select lives_ok($$select public.update_own_profile('Admin','Voiture','','N2','',true,2,'Parking habituel')$$,'Usual profile car defaults can be stored');
select is((select count(*) from public.car_offers),0::bigint,'Profile defaults never create an offer');
select throws_ok($$select public.offer_car((select id from sessions_fixture),1,'','')$$,'22023',null,'Unanswered member cannot offer a car');
select public.set_session_rsvp((select id from sessions_fixture),'yes');
select public.set_session_rsvp((select id from sessions_fixture),'yes',(select id from members_fixture where email='car.driver@example.test'));
select public.set_session_rsvp((select id from sessions_fixture),'yes',(select id from members_fixture where email='car.passenger@example.test'));
select public.set_session_rsvp((select id from sessions_fixture),'yes',(select id from members_fixture where email='car.other@example.test'));
insert into cars_fixture select 'A',public.offer_car((select id from sessions_fixture),1,'Parking','Note','20:00');
select is((select mode::text from public.get_session_transport((select id from sessions_fixture)) where member_id=public.current_member_id()),'driver','Driver mode is derived from an offer');
select is((select occupied from public.get_car_offers((select id from sessions_fixture))),0::bigint,'Driver consumes no passenger seat');
select throws_ok($$select public.join_car((select id from sessions_fixture),(select id from cars_fixture where name='A'))$$,'22023',null,'Driver cannot join own car');
select throws_ok($$select public.set_own_transport((select id from sessions_fixture),'driver')$$,'22023',null,'Member cannot claim a driver state without an offer');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000003',true);
select lives_ok($$select public.join_car((select id from sessions_fixture),(select id from cars_fixture where name='A'))$$,'Passenger takes first seat');
select lives_ok($$select public.join_car((select id from sessions_fixture),(select id from cars_fixture where name='A'))$$,'Retry on own occupied seat is idempotent');
select is((select occupied from public.get_car_offers((select id from sessions_fixture))),1::bigint,'Retry cannot duplicate seats');
select throws_ok($$select public.offer_car((select id from sessions_fixture),0,'','')$$,'23514',null,'Invalid new offer fails after attempting to release the passenger seat');
select is((select car_offer_id from public.car_passengers where member_id=public.current_member_id()),(select id from cars_fixture where name='A'),'Failed offer preserves the previous passenger seat transactionally');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000004',true);
select throws_ok($$select public.join_car((select id from sessions_fixture),(select id from cars_fixture where name='A'))$$,'22023',null,'A full car rejects another passenger');
select throws_ok($$delete from public.car_offers$$,'42501',null,'Browser cannot delete another driver offer');
select throws_ok($$insert into public.car_passengers values((select id from sessions_fixture),public.current_member_id(),(select id from cars_fixture where name='A'),now())$$,'42501',null,'Browser cannot bypass transactional seat RPC');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000001',true);
select lives_ok($$select public.offer_car((select id from sessions_fixture),2,'Parking','')$$,'Driver increases passenger capacity');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000004',true);
select lives_ok($$select public.join_car((select id from sessions_fixture),(select id from cars_fixture where name='A'))$$,'Second passenger joins after capacity increases');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000001',true);
select is((select occupied from public.get_car_offers((select id from sessions_fixture))),2::bigint,'Driver is excluded even when every passenger seat is occupied');
select throws_ok($$select public.offer_car((select id from sessions_fixture),1,'Parking','')$$,'22023',null,'Capacity cannot drop below occupancy');
select throws_ok($$select public.offer_car((select id from sessions_fixture),9,'','')$$,'23514',null,'At most eight passenger seats');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000002',true);
insert into cars_fixture select 'B',public.offer_car((select id from sessions_fixture),1,'Autre parking','');
select throws_ok($$select public.join_car((select id from sessions_fixture),(select id from cars_fixture where name='A'))$$,'22023',null,'Driver must remove offer before becoming a passenger');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000003',true);
select lives_ok($$select public.join_car((select id from sessions_fixture),(select id from cars_fixture where name='B'))$$,'Passenger can change cars atomically');
select is((select count(*) from public.car_passengers where member_id=public.current_member_id()),1::bigint,'Passenger occupies only one car per session');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000004',true);
select throws_ok($$select public.join_car((select id from sessions_fixture),(select id from cars_fixture where name='B'))$$,'22023',null,'Failed switch to full car is rejected');
select is((select car_offer_id from public.car_passengers where member_id=public.current_member_id()),(select id from cars_fixture where name='A'),'Failed switch preserves previous seat');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000003',true);
select lives_ok($$select public.set_own_transport((select id from sessions_fixture),'own')$$,'Passenger leaves car for own means');
select is((select mode::text from public.get_session_transport((select id from sessions_fixture)) where member_id=public.current_member_id()),'own','Manual transport is shown after leaving');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000004',true);
select public.join_car((select id from sessions_fixture),(select id from cars_fixture where name='B'));
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000002',true);
select lives_ok($$select public.set_session_rsvp((select id from sessions_fixture),'no',null,false,true)$$,'Driver withdraws from session');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000004',true);
select is((select rsvp::text from public.session_participations),'yes','Displaced passenger stays registered');
select is((select mode::text from public.get_session_transport((select id from sessions_fixture)) where member_id=public.current_member_id()),'needs','Displaced passenger needs reassignment');
select is((select count(*) from public.car_passengers where member_id=public.current_member_id()),0::bigint,'Withdrawn car releases its seat');
select lives_ok($$select public.set_own_transport((select id from sessions_fixture),'own')$$,'Displaced passenger may choose another transport');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000001',true);
select public.set_session_rsvp((select id from sessions_fixture),'yes',(select id from members_fixture where email='car.driver@example.test'));
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000002',true);
select public.offer_car((select id from sessions_fixture),1,'','');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000003',true);
select public.join_car((select id from sessions_fixture),(select id from public.car_offers where driver_member_id=(select id from members_fixture where email='car.driver@example.test')));
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000001',true);
select public.set_draft_selection((select id from sessions_fixture),(select id from members_fixture where email='car.driver@example.test'),'declined');
select is((select count(*) from public.car_offers),2::bigint,'Private declined draft leaves transport untouched');
select public.publish_selection((select id from sessions_fixture));
select is((select count(*) from public.car_offers),1::bigint,'Published driver exclusion removes only that car');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000003',true);
select is((select rsvp::text from public.session_participations),'yes','Exclusion of driver still preserves passenger RSVP');
select is((select mode::text from public.get_session_transport((select id from sessions_fixture)) where member_id=public.current_member_id()),'needs','Published driver exclusion marks passengers unresolved');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.offer_car((select id from sessions_fixture),1,'','')$$,'22023',null,'Published declined driver cannot recreate offer');
select throws_ok($$select email from public.get_car_offers((select id from sessions_fixture))$$,'42703',null,'Car projection reveals no private driver email');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000001',true);
insert into second_session_fixture select public.save_session('2030-11-01','21:00','22:00','Autre fosse','','','',20,true,false,false);
select public.set_session_rsvp((select id from second_session_fixture),'yes',(select id from members_fixture where email='car.passenger@example.test'));
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000003',true);
select throws_ok($$select public.join_car((select id from second_session_fixture),(select id from cars_fixture where name='A'))$$,'22023',null,'A car from another session cannot be joined');
reset role;
update public.sessions set status='closed',registration_open=false where id=(select id from second_session_fixture);
set local role authenticated;
select throws_ok($$select public.set_own_transport((select id from second_session_fixture),'own')$$,'22023',null,'Closed bilan prevents transport mutations');
select set_config('request.jwt.claim.sub','40000000-0000-4000-8000-000000000001',true);
select public.delete_session((select id from second_session_fixture));
select lives_ok($$select public.delete_session((select id from sessions_fixture))$$,'Session deletion cascades cars and seats');
select is((select count(*) from public.car_offers),0::bigint,'Deleted session has no offers');
reset role;
select * from finish();
rollback;
