begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('70000000-0000-4000-8000-000000000001','groups.member@example.test',now()),
('70000000-0000-4000-8000-000000000002','groups.admin@example.test',now()),
('70000000-0000-4000-8000-000000000003','groups.other@example.test',now());
select public.provision_member('70000000-0000-4000-8000-000000000001','Membre','Groupe');
select public.provision_member('70000000-0000-4000-8000-000000000002','Admin','Groupe');
select public.provision_member('70000000-0000-4000-8000-000000000003','Autre','Groupe');
update public.members set role='admin' where email='groups.admin@example.test';
create temp table group_members as select id,email from public.members where email like 'groups.%';
create temp table group_sessions(label text,id uuid);
grant select on group_members to authenticated;
grant select,insert on group_sessions to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','70000000-0000-4000-8000-000000000002',true);
insert into group_sessions values('main',public.save_session('2030-10-01','21:00','22:00','Palanquées','','','',2,true,false,false)),('other',public.save_session('2030-10-02','21:00','22:00','Autre','','','',2,true,false,false));
select throws_ok($$select public.set_draft_palanquee((select id from group_sessions where label='main'),public.current_member_id(),1)$$,'22023',null,'Groups require a published selection');
select public.set_session_rsvp((select id from group_sessions where label='main'),'yes',id) from group_members;
select public.set_draft_selection((select id from group_sessions where label='main'),id,'selected') from group_members where email<>'groups.other@example.test';
select public.publish_selection((select id from group_sessions where label='main'));
select throws_ok($$select public.set_draft_palanquee((select id from group_sessions where label='main'),(select id from group_members where email='groups.other@example.test'),1)$$,'22023',null,'Unselected Yes cannot be assigned');
select throws_ok($$select public.set_draft_palanquee((select id from group_sessions where label='main'),public.current_member_id(),9)$$,'23514',null,'Group numbers are bounded to 1–8');
select public.set_draft_palanquee((select id from group_sessions where label='main'),public.current_member_id(),1,true);
select public.set_draft_palanquee((select id from group_sessions where label='main'),(select id from group_members where email='groups.member@example.test'),1,false);
select is((select count(*) from public.palanquee_draft),2::bigint,'Both selected members have draft assignments');
select is((select count(*) from public.get_current_palanquees((select id from group_sessions where label='main'))),0::bigint,'Draft has no public effect');
select set_config('request.jwt.claim.sub','70000000-0000-4000-8000-000000000001',true);
select is((select count(*) from public.palanquee_draft),0::bigint,'Member cannot read draft contents');
select is((select count(*) from public.palanquee_drafts),0::bigint,'Member cannot read draft source/header');
select throws_ok($$select public.set_draft_palanquee((select id from group_sessions where label='main'),public.current_member_id(),1)$$,'42501',null,'Member cannot modify draft');
select throws_ok($$select public.publish_palanquees((select id from group_sessions where label='main'))$$,'42501',null,'Member cannot publish');
select throws_ok($$select public.ensure_palanquee_draft((select id from group_sessions where label='main'))$$,'42501',null,'Member cannot call internal draft helper');
select set_config('request.jwt.claim.sub','70000000-0000-4000-8000-000000000002',true);
select lives_ok($$select public.publish_palanquees((select id from group_sessions where label='main'))$$,'Admin publishes groups');
select is((select publication_version from public.get_palanquee_state((select id from group_sessions where label='main'))),1,'First version is one');
select is((select selection_version from public.get_palanquee_state((select id from group_sessions where label='main'))),1,'Groups link to source selection version');
select is((select needs_review from public.get_palanquee_state((select id from group_sessions where label='main'))),false,'Current selected population needs no review');
select is((select count(*) from public.palanquee_drafts),0::bigint,'Publishing consumes private draft');
select public.set_draft_palanquee((select id from group_sessions where label='main'),(select id from group_members where email='groups.member@example.test'),2,true);
select is((select group_number from public.get_current_palanquees((select id from group_sessions where label='main')) where member_id=(select id from group_members where email='groups.member@example.test')),1,'Previous groups remain visible during draft');
reset role;
select throws_ok($$update public.palanquee_publication_members set group_number=2$$,'23514',null,'Group snapshots are immutable');
select throws_ok($$update public.palanquee_publications set version=99$$,'23514',null,'Group header versions are immutable');
select throws_ok($$update public.palanquee_publications set selection_publication_id=gen_random_uuid()$$,'23514',null,'Group source selection cannot be rewritten');
select throws_ok($$update public.palanquee_publications set id=gen_random_uuid()$$,'23514',null,'Snapshot identifier is immutable');
select throws_ok($$update public.palanquee_publications set published_by=null$$,'23514',null,'Actor provenance cannot be erased while member exists');
select throws_ok($$delete from public.palanquee_publication_members$$,'23514',null,'Group snapshots cannot be independently deleted');
select throws_ok($$delete from public.palanquee_publications$$,'23514',null,'Group header cannot be independently deleted');
create function pg_temp.reject_groups_audit() returns trigger language plpgsql as $$begin if new.event_type='palanquees_published' then raise exception 'Injected groups audit failure'; end if; return new; end;$$;
create trigger inject_groups_failure before insert on public.audit_events for each row execute function pg_temp.reject_groups_audit();
set local role authenticated;
select throws_ok($$select public.publish_palanquees((select id from group_sessions where label='main'))$$,'P0001','Injected groups audit failure','Failed audit rolls back publication');
select is((select max(version) from public.palanquee_publications),1,'Failed publication creates no version');
select is((select count(*) from public.palanquee_draft),2::bigint,'Failed publication preserves draft assignments');
reset role;
drop trigger inject_groups_failure on public.audit_events;
set local role authenticated;
select public.publish_palanquees((select id from group_sessions where label='main'));
select is((select publication_version from public.get_palanquee_state((select id from group_sessions where label='main'))),2,'Republication creates version two');
select is((select group_number from public.palanquee_publication_members pm join public.palanquee_publications p on p.id=pm.publication_id where p.version=1 and pm.member_id=(select id from group_members where email='groups.member@example.test')),1,'Version one remains unchanged');
select set_config('request.jwt.claim.sub','70000000-0000-4000-8000-000000000001',true);
select public.update_own_profile('Membre','Groupe','', 'MF1','',false,0,'');
select is((select current_level from public.get_current_palanquees((select id from group_sessions where label='main')) where member_id=public.current_member_id()),'MF1','Published summary reads live profile levels');
select public.set_session_rsvp((select id from group_sessions where label='main'),'no',null,false,true);
select is((select count(*) from public.get_current_palanquees((select id from group_sessions where label='main'))),1::bigint,'Withdrawal removes current assignment without editing history');
select is((select needs_review from public.get_palanquee_state((select id from group_sessions where label='main'))),true,'Withdrawal marks groups for review');
select is((select count(*) from public.palanquee_publication_members),4::bigint,'Withdrawn historical snapshots remain');
select public.set_session_rsvp((select id from group_sessions where label='main'),'yes',null,true);
select set_config('request.jwt.claim.sub','70000000-0000-4000-8000-000000000002',true);
select public.set_draft_selection((select id from group_sessions where label='main'),(select id from group_members where email='groups.member@example.test'),'selected');
select public.publish_selection((select id from group_sessions where label='main'));
select is((select count(*) from public.get_current_palanquees((select id from group_sessions where label='main'))),1::bigint,'New selection does not resurrect withdrawn member old group');
select public.set_draft_palanquee((select id from group_sessions where label='main'),public.current_member_id(),2,true);
select is((select count(*) from public.palanquee_draft),1::bigint,'New draft never pre-fills a withdrawn old assignment');
select public.publish_selection((select id from group_sessions where label='main'));
select throws_ok($$select public.publish_palanquees((select id from group_sessions where label='main'))$$,'22023',null,'Selection version changed during draft requires explicit review');
select lives_ok($$select public.discard_palanquee_draft((select id from group_sessions where label='main'))$$,'Admin abandons stale draft');
select public.set_draft_palanquee((select id from group_sessions where label='main'),(select id from group_members where email='groups.member@example.test'),3,false);
select public.publish_palanquees((select id from group_sessions where label='main'));
select is((select selection_version from public.get_palanquee_state((select id from group_sessions where label='main'))),3,'New publication links the latest selection');
select public.set_draft_palanquee((select id from group_sessions where label='main'),(select id from group_members where email='groups.member@example.test'),null,false);
select public.publish_palanquees((select id from group_sessions where label='main'));
select is((select count(*) from public.get_current_palanquees((select id from group_sessions where label='main'))),1::bigint,'Unassigned confirmed members are allowed and remain visible in selection');
select public.publish_selection((select id from group_sessions where label='other'));
reset role;
select throws_ok($$insert into public.palanquee_publications(session_id,version,selection_publication_id) values((select id from group_sessions where label='main'),99,(select id from public.selection_publications where session_id=(select id from group_sessions where label='other')))$$,'23503',null,'Publication source must belong to same session');
update public.sessions set status='closed',registration_open=false where id=(select id from group_sessions where label='main');
set local role authenticated;
select throws_ok($$select public.set_draft_palanquee((select id from group_sessions where label='main'),public.current_member_id(),1)$$,'22023',null,'Closed bilan protects group edits');
select throws_ok($$insert into public.palanquee_draft(session_id,member_id,group_number) values((select id from group_sessions where label='main'),public.current_member_id(),1)$$,'42501',null,'Browser cannot bypass draft RPC');
select throws_ok($$select email from public.get_current_palanquees((select id from group_sessions where label='main'))$$,'42703',null,'Public groups reveal no private profile email');
reset role;
update public.members set role='member' where email='groups.admin@example.test';
set local role authenticated;
select throws_ok($$select public.set_draft_palanquee((select id from group_sessions where label='main'),public.current_member_id(),1)$$,'42501',null,'Revoked admin loses group editing with same JWT');
select throws_ok($$select public.publish_palanquees((select id from group_sessions where label='main'))$$,'42501',null,'Revoked admin loses publication rights with same JWT');
select throws_ok($$select public.discard_palanquee_draft((select id from group_sessions where label='main'))$$,'42501',null,'Revoked admin cannot delete private draft');
reset role;
update public.members set role='admin' where email='groups.admin@example.test';
set local role authenticated;
select lives_ok($$select public.delete_session((select id from group_sessions where label='main'))$$,'Session deletion cascades all group history');
select is((select count(*) from public.palanquee_publications),0::bigint,'Whole-session deletion removes snapshots');
select public.publish_palanquees((select id from group_sessions where label='other'));
reset role;
select lives_ok($$delete from public.members where id=(select id from group_members where email='groups.admin@example.test')$$,'Trusted actor erasure can anonymize historical headers');
select is((select count(*) from public.palanquee_publications where published_by is null),1::bigint,'Erased actor provenance becomes anonymous, with snapshot retained');
select is((select version from public.palanquee_publications),1,'Actor anonymization preserves the version');
select lives_ok($$delete from public.sessions where id=(select id from group_sessions where label='other')$$,'Whole-session cascade works after actor erasure');
set local role anon;
select throws_ok($$select public.get_current_palanquees('00000000-0000-4000-8000-000000000001')$$,'42501',null,'Anonymous cannot read groups');
reset role;
select * from finish();
rollback;
