begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('50000000-0000-4000-8000-000000000001','payment.member@example.test',now()),
('50000000-0000-4000-8000-000000000002','payment.admin@example.test',now());
select public.provision_member('50000000-0000-4000-8000-000000000001','Membre','Paiement');
select public.provision_member('50000000-0000-4000-8000-000000000002','Admin','Paiement');
update public.members set role='admin' where email='payment.admin@example.test';
create temp table payment_members as select id,email from public.members where email like 'payment.%';
create temp table payment_session(id uuid);
grant select on payment_members to authenticated;
grant select,insert on payment_session to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','50000000-0000-4000-8000-000000000002',true);
insert into payment_session select public.save_session('2030-10-01','21:00','22:00','Paiement','','','',2,true,false,false);
select public.set_session_rsvp((select id from payment_session),'yes',(select id from payment_members where email='payment.member@example.test'));
select lives_ok($$select public.set_payment_status((select id from payment_session),(select id from payment_members where email='payment.member@example.test'),'paid')$$,'Admin records a payment');
select public.set_payment_status((select id from payment_session),(select id from payment_members where email='payment.member@example.test'),'paid');
select is((select count(*) from public.audit_events where session_id=(select id from payment_session) and event_type='payment_changed'),1::bigint,'Idempotent payment retry creates one audit');
select is((select count(*) from public.get_admin_readiness((select id from payment_session)) where payment_ready),1::bigint,'Paid is ready');
select is((select count(*) from public.get_admin_readiness((select id from payment_session)) where selection_ready or caci_ready or transport_ready),0::bigint,'Payment alone never makes the other criteria ready');
select public.set_draft_selection((select id from payment_session),(select id from payment_members where email='payment.member@example.test'),'selected');
select public.set_member_caci((select id from payment_members where email='payment.member@example.test'),'2030-10-01');
select is((select caci_status from public.get_admin_readiness((select id from payment_session))),'soon','Expiry on session date remains valid');
select is((select count(*) from public.get_admin_readiness((select id from payment_session)) where selection_ready and caci_ready),1::bigint,'Readiness uses private draft and session-date CACI');
reset role;
create function pg_temp.reject_payment_audit() returns trigger language plpgsql as $$begin if new.event_type='payment_changed' then raise exception 'Injected payment audit failure'; end if; return new; end;$$;
create trigger inject_payment_failure before insert on public.audit_events for each row execute function pg_temp.reject_payment_audit();
set local role authenticated;
select throws_ok($$select public.set_payment_status((select id from payment_session),(select id from payment_members where email='payment.member@example.test'),'free')$$,'P0001','Injected payment audit failure','Audit failure rolls back payment write');
select is((select payment_status::text from public.session_participations where member_id=(select id from payment_members where email='payment.member@example.test')),'paid','Failed payment correction preserves previous status');
reset role;
drop trigger inject_payment_failure on public.audit_events;
set local role authenticated;
select set_config('request.jwt.claim.sub','50000000-0000-4000-8000-000000000001',true);
select public.set_own_transport((select id from payment_session),'own');
select is((select payment_status::text from public.session_participations where session_id=(select id from payment_session)),'paid','Member sees own payment');
select throws_ok($$select public.set_payment_status((select id from payment_session),public.current_member_id(),'free')$$,'42501',null,'Member cannot edit own payment');
select throws_ok($$select public.set_payment_status((select id from payment_session),(select id from payment_members where email='payment.admin@example.test'),'paid')$$,'42501',null,'Member cannot edit another payment');
select throws_ok($$select public.get_admin_readiness((select id from payment_session))$$,'42501',null,'Member cannot read private readiness');
select throws_ok($$update public.session_participations set payment_status='free'$$,'42501',null,'Direct browser payment updates are forbidden');
select throws_ok($$select payment_status from public.get_session_responses((select id from payment_session))$$,'42703',null,'Public response projection has no payment');
select throws_ok($$select payment_status from public.get_current_selection((select id from payment_session))$$,'42703',null,'Public selection projection has no payment');
select throws_ok($$select payment_status from public.get_session_transport((select id from payment_session))$$,'42703',null,'Public transport projection has no payment');
select set_config('request.jwt.claim.sub','50000000-0000-4000-8000-000000000002',true);
select is((select count(*) from public.get_admin_readiness((select id from payment_session)) where selection_ready and caci_ready and transport_ready and payment_ready),1::bigint,'All four live criteria make member ready');
select public.set_member_caci((select id from payment_members where email='payment.member@example.test'),'2030-09-30');
select is((select caci_status from public.get_admin_readiness((select id from payment_session))),'expired','Certificate expiring before future session is not ready');
select public.set_payment_status((select id from payment_session),(select id from payment_members where email='payment.member@example.test'),'free');
select is((select payment_ready from public.get_admin_readiness((select id from payment_session))),true,'Free is ready');
select public.set_payment_status((select id from payment_session),(select id from payment_members where email='payment.admin@example.test'),'paid');
select is((select rsvp::text from public.session_participations where member_id=public.current_member_id() and session_id=(select id from payment_session)),'unanswered','Payment never registers an unanswered member');
select is((select count(*) from public.get_admin_readiness((select id from payment_session))),1::bigint,'Only Yes and Maybe belong in readiness');
select set_config('request.jwt.claim.sub','50000000-0000-4000-8000-000000000001',true);
select is((select count(*) from public.session_participations where member_id=(select id from payment_members where email='payment.admin@example.test')),0::bigint,'Another member payment is hidden by RLS');
reset role;
update public.sessions set status='closed',registration_open=false where id=(select id from payment_session);
set local role authenticated;
select set_config('request.jwt.claim.sub','50000000-0000-4000-8000-000000000002',true);
select lives_ok($$select public.set_payment_status((select id from payment_session),(select id from payment_members where email='payment.member@example.test'),'unpaid')$$,'Admin can correct payment after session closure');
select is((select payment_ready from public.get_admin_readiness((select id from payment_session))),false,'Correction immediately changes derived readiness');
select is((select rsvp::text from public.session_participations where member_id=(select id from payment_members where email='payment.member@example.test')),'yes','Payment correction preserves RSVP');
select is((select attendance_status::text from public.session_participations where member_id=(select id from payment_members where email='payment.member@example.test')),'unknown','Payment correction preserves attendance');
reset role;
update public.members set role='president' where email='payment.admin@example.test';
set local role authenticated;
select lives_ok($$select public.set_payment_status((select id from payment_session),public.current_member_id(),'free')$$,'President can update payment');
select lives_ok($$select public.get_admin_readiness((select id from payment_session))$$,'President can read readiness');
reset role;
update public.members set role='member' where email='payment.admin@example.test';
set local role authenticated;
select throws_ok($$select public.get_admin_readiness((select id from payment_session))$$,'42501',null,'Revoked admin loses readiness access with same JWT');
select throws_ok($$select public.set_payment_status((select id from payment_session),public.current_member_id(),'free')$$,'42501',null,'Revoked admin loses payment writes with same JWT');
reset role;
set local role anon;
select throws_ok($$select public.get_admin_readiness('00000000-0000-4000-8000-000000000001')$$,'42501',null,'Anonymous readiness access is forbidden');
select throws_ok($$select public.set_payment_status('00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000001','paid')$$,'42501',null,'Anonymous payment writes are forbidden');
reset role;
select * from finish();
rollback;
