begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create temp table people(label text,id uuid,auth_id uuid);
grant select on people to authenticated,service_role,anon;
insert into auth.users(id,email,email_confirmed_at)
select ('10000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'presidency-'||i||'@example.test',now() from generate_series(1,10) i;
insert into people select 'person'||i,public.provision_member(('10000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid,'Personne '||i,'Fictive'),('10000000-0000-4000-8000-'||lpad(i::text,12,'0'))::uuid from generate_series(1,10) i;
select public.bootstrap_president((select id from people where label='person1'));
update auth.users set email='fictif@ifosse-seed.invalid' where id=(select auth_id from people where label='person10');
update public.members set email='fictif@ifosse-seed.invalid' where id=(select id from people where label='person10');
update public.members set role='admin' where id=(select id from people where label='person3');
update public.members set disabled_at=now() where id=(select id from people where label='person4');
update auth.users set banned_until=now()+interval '1 day' where id=(select auth_id from people where label='person5');
update auth.users set deleted_at=now() where id=(select auth_id from people where label='person6');
update auth.users set email_confirmed_at=null where id=(select auth_id from people where label='person7');
update auth.users set email='different-presidency@example.test' where id=(select auth_id from people where label='person9');
update public.members set auth_user_id=null where id=(select id from people where label='person8');
create temp table snapshot as select updated_at from public.members where id=(select id from people where label='person2');
grant select on snapshot to authenticated;
set local role anon;
select throws_ok($$select public.transfer_presidency_if_current((select id from people where label='person2'),now())$$,'42501',null,'Anonymous cannot invoke checked transfer');
reset role;
set local role service_role;
select throws_ok($$select public.transfer_presidency_if_current((select id from people where label='person2'),now())$$,'42501',null,'Service cannot use application transfer; recovery remains separate');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select auth_id::text from people where label='person2'),true);
select set_config('request.jwt.claims','{"role":"authenticated","app_metadata":{"role":"president"}}',true);
select throws_ok($$select public.transfer_presidency_if_current((select id from people where label='person3'),now())$$,'42501',null,'Member cannot transfer using forged metadata');
select set_config('request.jwt.claim.sub',(select auth_id::text from people where label='person3'),true);
select throws_ok($$select public.transfer_presidency_if_current((select id from people where label='person2'),now())$$,'42501',null,'Admin cannot transfer');
select set_config('request.jwt.claim.sub',(select auth_id::text from people where label='person1'),true);
select throws_ok($$select public.transfer_presidency_if_current(null,now())$$,'22023',null,'Null target refused');
select throws_ok($$select public.transfer_presidency_if_current((select id from people where label='person1'),now())$$,'22023',null,'Self-transfer refused');
select throws_ok($$select public.transfer_presidency_if_current((select id from people where label='person2'),null)$$,'22023',null,'Missing snapshot refused');
select throws_ok($$select public.transfer_presidency_if_current('ffffffff-ffff-4fff-8fff-ffffffffffff',now())$$,'22023',null,'Missing member refused');
select throws_ok($$select public.transfer_presidency((select id from people where label='person4'))$$,'22023','SUCCESSOR_UNAVAILABLE','Legacy transfer also rejects disabled profiles explicitly');
select throws_ok($$select public.transfer_presidency((select id from people where label='person5'))$$,'22023',null,'Auth banned target refused');
select throws_ok($$select public.transfer_presidency((select id from people where label='person6'))$$,'22023',null,'Auth deleted target refused');
select throws_ok($$select public.transfer_presidency((select id from people where label='person7'))$$,'22023',null,'Unconfirmed Auth target refused');
select throws_ok($$select public.transfer_presidency((select id from people where label='person10'))$$,'22023',null,'Reserved fictitious .invalid successor refused without modifying seed ownership');
select throws_ok($$select public.transfer_presidency((select id from people where label='person9'))$$,'22023',null,'Mismatched Auth/profile email refused');
select throws_ok($$select public.transfer_presidency((select id from people where label='person8'))$$,'22023',null,'Unlinked target refused');
select throws_ok($$select public.transfer_presidency_if_current((select id from people where label='person2'),(select updated_at-interval '1 second' from snapshot))$$,'40001','SUCCESSOR_CHANGED','Stale snapshot refused');
select is(public.is_president(),true,'Failed transfers preserve caller presidency');
select is((select count(*) from public.audit_events where event_type='presidency_transferred'),0::bigint,'Refused requests do not audit a successful transfer');
reset role;
update auth.users set banned_until=now()+interval '1 day' where id=(select auth_id from people where label='person1');
set local role authenticated;
select throws_ok($$select public.transfer_presidency_if_current((select id from people where label='person2'),(select updated_at from snapshot))$$,'42501',null,'Banned caller cannot transfer even with a stale President token');
reset role;
update auth.users set banned_until=null where id=(select auth_id from people where label='person1');
-- An audit failure occurs after BOTH role changes, and must roll both back.
create function pg_temp.fail_transfer_audit() returns trigger language plpgsql as $$begin if new.event_type='presidency_transferred' then raise exception using errcode='P0001',message='Injected audit failure'; end if;return new;end;$$;
create trigger test_transfer_audit before insert on public.audit_events for each row execute function pg_temp.fail_transfer_audit();
set local role authenticated;
select throws_ok($$select public.transfer_presidency_if_current((select id from people where label='person2'),(select updated_at from snapshot))$$,'P0001','Injected audit failure','Late failure rolls back full transfer');
select is(public.is_president(),true,'Audit failure preserves former President');
select is((select role::text from public.members where id=(select id from people where label='person2')),'member','Audit failure does not promote successor');
reset role;
drop trigger test_transfer_audit on public.audit_events;
set local role authenticated;
select lives_ok($$select public.transfer_presidency_if_current((select id from people where label='person2'),(select updated_at from snapshot))$$,'President can transfer to ordinary member');
select is(public.current_member_role()::text,'admin','Former President becomes admin');
select is(public.is_president(),false,'Stale JWT immediately loses presidency');
select throws_ok($$select public.set_member_active((select id from people where label='person3'),false)$$,'42501',null,'Former President cannot suspend accounts');
select throws_ok($$select public.set_member_role((select id from people where label='person3'),'member')$$,'42501',null,'Former President cannot manage roles');
select throws_ok($$select public.transfer_presidency_if_current((select id from people where label='person3'),now())$$,'42501',null,'Replay/second request cannot transfer again');
select set_config('request.jwt.claim.sub',(select auth_id::text from people where label='person2'),true);
select is(public.is_president(),true,'New President effective without token refresh');
select is((select count(*) from public.members where role='president'),1::bigint,'Exactly one President remains');
select is((select count(*) from public.audit_events where event_type='presidency_transferred'),1::bigint,'One successful audit');
select is((select actor_member_id from public.audit_events where event_type='presidency_transferred'),(select id from people where label='person1'),'Audit identifies former President');
select is((select target_member_id from public.audit_events where event_type='presidency_transferred'),(select id from people where label='person2'),'Audit identifies successor');
select is((select payload->>'previous_target_role' from public.audit_events where event_type='presidency_transferred'),'member','Audit preserves previous successor role');
select throws_ok($$select public.set_member_role(public.current_member_id(),'member')$$,'23514',null,'New sole President cannot be demoted');
select throws_ok($$select public.set_member_active(public.current_member_id(),false)$$,'23514',null,'New sole President cannot be disabled');
select lives_ok($$select public.transfer_presidency_if_current((select id from people where label='person3'),(select updated_at from public.members where id=(select id from people where label='person3')))$$,'Transfer also accepts active admin');
select is((select count(*) from public.members where role='president'),1::bigint,'Admin handover retains sole President');
select is((select disabled_at from public.members where id=(select id from people where label='person4')) is not null,true,'Other lifecycle states preserved');
reset role;
set local role service_role;
select lives_ok($$select public.recover_president((select id from people where label='person1'),'Reprise fictive après transfert pour test opérateur')$$,'Operator recovery remains available');
select is((select count(*) from public.members where role='president'),1::bigint,'Recovery retains single President');
reset role;
select * from finish();rollback;
