begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('a0000000-0000-4000-8000-000000000001','occupancy.admin@example.test',now()),
('a0000000-0000-4000-8000-000000000002','occupancy.member@example.test',now());
select public.provision_member('a0000000-0000-4000-8000-000000000001','Admin','Occupancy');
select public.provision_member('a0000000-0000-4000-8000-000000000002','Membre','Occupancy');
update public.members set role='admin' where email='occupancy.admin@example.test';
create temp table occupancy_members as select id,email from public.members where email like 'occupancy.%';
create temp table occupancy_sessions(id uuid,label text);
grant select on occupancy_members to authenticated;
grant select,insert on occupancy_sessions to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000001',true);
insert into occupancy_sessions select public.save_session('2030-10-01','21:00','22:00','Occupancy','','','',20,true,false,false),'main';
insert into occupancy_sessions select public.save_session('2030-11-01','21:00','22:00','Empty','','','',20,true,false,false),'empty';
insert into occupancy_sessions select public.save_session('2031-10-01','21:00','22:00','Other season','','','',20,true,false,false),'other';
select is((select count(*) from public.get_session_card_summaries(2030)),2::bigint,'Seasonal projection batches all relevant cards');
select ok((select publication_version=0 and confirmed_count=0 and capacity=20 from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'No publication is explicitly different from zero confirmed');
select ok((select my_rsvp='unanswered' and my_selection_state='none' and my_transport_mode='unset' and my_payment_status is null from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'Unanswered card has no fictitious payment');
select public.set_session_rsvp((select id from occupancy_sessions where label='main'),'yes',id) from occupancy_members;
select public.set_draft_selection((select id from occupancy_sessions where label='main'),public.current_member_id(),'selected');
select is((select publication_version from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),0,'First private draft is not published occupancy');
select public.publish_selection((select id from occupancy_sessions where label='main'));
select ok((select publication_version=1 and confirmed_count=1 from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'First publication is counted');
select public.set_draft_selection((select id from occupancy_sessions where label='main'),(select id from occupancy_members where email='occupancy.member@example.test'),'selected');
select is((select confirmed_count from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),1::bigint,'New private draft cannot change published count');
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000002',true);
select is((select confirmed_count from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),1::bigint,'Member sees same published count as admin');
select ok((select my_rsvp='yes' and my_selection_state='waiting' and my_payment_status='unpaid' from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'Private draft cannot confirm the member card');
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000001',true);
select public.publish_selection((select id from occupancy_sessions where label='main'));
select ok((select publication_version=2 and confirmed_count=2 from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'Republication replaces count');
select ok((select my_selection_state='selected' from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'Own published confirmation appears');
select public.offer_car((select id from occupancy_sessions where label='main'),2,'Rendez-vous fictif','','20:00');
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000002',true);
select public.join_car((select id from occupancy_sessions where label='main'),(select id from public.get_car_offers((select id from occupancy_sessions where label='main')) limit 1));
select ok((select my_transport_mode='passenger' and not my_transport_provisional from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'Passenger with published driver is resolved');
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000001',true);
select public.set_session_rsvp((select id from occupancy_sessions where label='main'),'no',(select id from occupancy_members where email='occupancy.member@example.test'),false,true);
select is((select confirmed_count from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),1::bigint,'Withdrawal removes effective confirmation without rewriting snapshot');
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000002',true);
select ok((select my_rsvp='no' and my_selection_state='withdrawn' and my_payment_status is null and my_transport_mode='unset' from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'Withdrawal card has no fictitious debt or reservation');
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000001',true);
select public.set_session_rsvp((select id from occupancy_sessions where label='main'),'yes',(select id from occupancy_members where email='occupancy.member@example.test'));
select is((select confirmed_count from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),1::bigint,'Returning Yes does not restore an obsolete confirmation');
select public.publish_selection((select id from occupancy_sessions where label='empty'));
select ok((select publication_version=1 and confirmed_count=0 from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='empty')),'Empty publication is genuinely zero confirmed');
select throws_ok($$select public.get_session_card_summaries(null)$$,'22023',null,'Invalid season rejected');
reset role;
set local role anon;
select throws_ok($$select public.get_session_card_summaries(2030)$$,'42501',null,'Anonymous summaries denied');
reset role;
-- Explicitly distinguish personal payments even for an administrator.
update public.session_participations set payment_status='paid' where member_id=(select id from occupancy_members where email='occupancy.member@example.test');
set local role authenticated;
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000001',true);
select is((select my_payment_status::text from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'unpaid','Admin projection contains only their own payment');
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000002',true);
select is((select my_payment_status::text from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'paid','Member projection contains their own payment');
select public.offer_car((select id from occupancy_sessions where label='main'),2,'Rendez-vous fictif','','20:00');
select ok((select my_transport_mode='driver' and my_transport_provisional from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'Returning Yes driver remains provisional until republication');
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000001',true);
select public.set_own_transport((select id from occupancy_sessions where label='main'),'needs');
select public.join_car((select id from occupancy_sessions where label='main'),(select id from public.get_car_offers((select id from occupancy_sessions where label='main')) limit 1));
select ok((select my_transport_mode='passenger' and my_transport_provisional from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'Passenger of unconfirmed driver is provisional');
select public.set_draft_selection((select id from occupancy_sessions where label='main'),(select id from occupancy_members where email='occupancy.member@example.test'),'selected');
select public.publish_selection((select id from occupancy_sessions where label='main'));
select ok((select not my_transport_provisional from public.get_session_card_summaries(2030) where session_id=(select id from occupancy_sessions where label='main')),'Republication resolves transport without client business rules');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000099',true);
select throws_ok($$select public.get_session_card_summaries(2030)$$,'42501',null,'Unprovisioned authenticated identity denied');
reset role;
update public.members set disabled_at=now() where email='occupancy.member@example.test';
set local role authenticated;
select set_config('request.jwt.claim.sub','a0000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.get_session_card_summaries(2030)$$,'42501',null,'Inactive identity denied even with a previous token');
reset role;
select ok(position('p_member_id' in pg_get_function_arguments('public.get_session_card_summaries(integer)'::regprocedure))=0,'Projection accepts no target member');
select * from finish();
rollback;
