begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create temp table calendar_input(payload jsonb);
insert into calendar_input values('[{"date":"2026-10-28","start_time":"21:00","end_time":"22:00","end_time_estimated":false,"school_holiday":true,"title":"Séance de fosse","venue":"Villeneuve","address":"","notes":""},{"date":"2026-11-04","start_time":"22:00","end_time":"23:00","end_time_estimated":true,"school_holiday":false,"title":"Séance de fosse","venue":"Villeneuve","address":"","notes":""}]');
grant select on calendar_input to authenticated,service_role;
set local role authenticated;
select throws_ok($$select public.import_season_calendar((select payload from calendar_input))$$,'42501',null,'Browser cannot import calendar with a regular or admin JWT');
reset role;
set local role service_role;
select lives_ok($$select public.import_season_calendar((select payload from calendar_input))$$,'Trusted operator imports reviewed real sessions');
select is((select count(*) from public.sessions where import_source_key is not null),2::bigint,'Import creates only source sessions');
select is((select count(*) from public.session_participations),0::bigint,'Import creates no fictitious registrations');
select is((select count(*) from public.selection_publications),0::bigint,'Import creates no demo selection');
select is((select count(*) from public.audit_events where event_type='calendar_imported' and session_id in(select id from public.sessions where import_source_key is not null)),2::bigint,'Each imported session is audited');
select is((select count(*) from public.import_season_calendar((select payload from calendar_input)) where created),0::bigint,'Retry retains imported rows without duplication');
reset role;
update public.sessions set capacity=30,notes='Correction organisateur' where date='2026-10-28';
set local role service_role;
select public.import_season_calendar((select payload from calendar_input));
select is((select capacity from public.sessions where date='2026-10-28'),30,'Retry never overwrites later administrator capacity');
select is((select notes from public.sessions where date='2026-10-28'),'Correction organisateur','Retry never overwrites later administrator notes');
select throws_ok($$select public.import_season_calendar(jsonb_set((select payload from calendar_input),'{0,title}','"Source modifiée"'))$$,'22023',null,'Changed source fingerprint requires operator review');
select throws_ok($$select public.import_season_calendar(jsonb_set((select payload from calendar_input),'{0,date}','"2026-09-09"'))$$,'22023',null,'Fictitious historical date rejected');
select throws_ok($$select public.import_season_calendar((select payload->0 from calendar_input))$$,'22023',null,'Non-array input rejected');
select throws_ok($$select public.import_season_calendar((select jsonb_build_array(payload->0,payload->0) from calendar_input))$$,'22023',null,'Duplicate dates rejected atomically');
reset role;
delete from public.sessions where import_source_key is not null;
set local role service_role;
select throws_ok($$select public.import_season_calendar(jsonb_set((select payload from calendar_input),'{1,end_time}','"20:00"'))$$,'23514',null,'Invalid final entry aborts whole transactional import');
select is((select count(*) from public.sessions),0::bigint,'Failed final entry creates no partial first session');
reset role;
insert into public.sessions(date,start_time,end_time,title) values('2026-10-28','21:00','22:00','Créée manuellement');
set local role service_role;
select throws_ok($$select public.import_season_calendar((select payload from calendar_input))$$,'22023',null,'Existing manual session cannot be duplicated silently');
reset role;
set local role anon;
select throws_ok($$select public.import_season_calendar('[]')$$,'42501',null,'Anonymous imports forbidden');
reset role;
select * from finish();
rollback;
