begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('30000000-0000-4000-8000-000000000001','selection.member@example.test',now()),
('30000000-0000-4000-8000-000000000002','selection.admin@example.test',now()),
('30000000-0000-4000-8000-000000000003','selection.other@example.test',now());
select public.provision_member('30000000-0000-4000-8000-000000000001','Membre','Test');
select public.provision_member('30000000-0000-4000-8000-000000000002','Admin','Test');
select public.provision_member('30000000-0000-4000-8000-000000000003','Autre','Test');
update public.members set role='admin' where email='selection.admin@example.test';
create temp table members_fixture as select id,email from public.members where email like 'selection.%';
create temp table sessions_fixture(id uuid);
grant select on members_fixture to authenticated;
grant select,insert on sessions_fixture to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000002',true);
insert into sessions_fixture select public.save_session('2030-10-01','21:00','22:00','Sélection','','','',2,true,false,false);
select public.set_session_rsvp((select id from sessions_fixture),'yes');
select public.set_session_rsvp((select id from sessions_fixture),'yes',(select id from members_fixture where email='selection.member@example.test'));
select public.set_session_rsvp((select id from sessions_fixture),'maybe',(select id from members_fixture where email='selection.other@example.test'));
select lives_ok($$select public.set_draft_selection((select id from sessions_fixture),public.current_member_id(),'selected')$$,'Admin selects a Yes response in private draft');
select lives_ok($$select public.set_draft_selection((select id from sessions_fixture),(select id from members_fixture where email='selection.member@example.test'),'selected')$$,'Instructors/members all consume one capacity slot');
select throws_ok($$select public.set_draft_selection((select id from sessions_fixture),(select id from members_fixture where email='selection.other@example.test'),'selected')$$,'22023',null,'Maybe cannot be selected');
select is((select count(*) from public.selection_publications),0::bigint,'Draft changes create no publication');
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000001',true);
select is((select count(*) from public.selection_draft),0::bigint,'Member cannot read any draft content');
select is((select count(*) from public.selection_drafts),0::bigint,'Member cannot infer draft header state');
select throws_ok($$select public.ensure_selection_draft((select id from sessions_fixture))$$,'42501',null,'Member cannot call internal draft initializer');
select throws_ok($$select public.set_draft_selection((select id from sessions_fixture),public.current_member_id(),'selected')$$,'42501',null,'Member cannot modify a draft');
select throws_ok($$select public.publish_selection((select id from sessions_fixture))$$,'42501',null,'Member cannot publish');
select is((select state from public.get_current_selection((select id from sessions_fixture)) where member_id=public.current_member_id()),'pending','Unpublished selection stays pending');
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000002',true);
select lives_ok($$select public.publish_selection((select id from sessions_fixture))$$,'Admin publishes atomically');
select is((select max(version) from public.selection_publications),1,'First publication version is one');
select is((select count(*) from public.selection_drafts),0::bigint,'Publication consumes draft header/content');
select lives_ok($$select public.set_draft_selection((select id from sessions_fixture),(select id from members_fixture where email='selection.member@example.test'),'waiting')$$,'New draft begins from the current publication');
select is((select count(*) from public.get_current_selection((select id from sessions_fixture)) where state='selected'),2::bigint,'Previous publication remains selected while draft changes');
select throws_ok($$select public.save_session('2030-10-01','21:00','22:00','Sélection','','','',1,true,false,false,(select id from sessions_fixture))$$,'22023',null,'Capacity reduction must respect current publication as well as draft');
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000001',true);
select lives_ok($$select public.set_session_rsvp((select id from sessions_fixture),'no',null,false,true)$$,'Selected member withdraws without editing history');
select is((select state from public.get_current_selection((select id from sessions_fixture)) where member_id=public.current_member_id()),'withdrawn','Published projection marks the withdrawal');
select is((select state::text from public.selection_publication_members where member_id=public.current_member_id()),'selected','Historical snapshot retains selected state');
select lives_ok($$select public.set_session_rsvp((select id from sessions_fixture),'yes',null,true)$$,'Withdrawn member may register Yes again');
select is((select state from public.get_current_selection((select id from sessions_fixture)) where member_id=public.current_member_id()),'waiting','A new Yes never resurrects an old published place');
select set_config('request.jwt.claim.sub','30000000-0000-4000-8000-000000000002',true);
select lives_ok($$select public.save_session('2030-10-01','21:00','22:00','Sélection','','','',1,true,false,false,(select id from sessions_fixture))$$,'Released effective place allows capacity reduction');
select throws_ok($$select public.set_draft_selection((select id from sessions_fixture),(select id from members_fixture where email='selection.member@example.test'),'selected')$$,'22023',null,'Draft cannot exceed current capacity');
select lives_ok($$select public.save_session('2030-10-01','21:00','22:00','Sélection','','','',2,true,false,false,(select id from sessions_fixture))$$,'Admin increases capacity before confirming another member');
select lives_ok($$select public.set_draft_selection((select id from sessions_fixture),(select id from members_fixture where email='selection.member@example.test'),'selected')$$,'Explicit new selection confirms re-registered member');
reset role;
select throws_ok($$update public.selection_publication_members set state='waiting'$$,'23514',null,'Snapshot content cannot be mutated even by a direct SQL update');
select throws_ok($$update public.selection_publications set version=99$$,'23514',null,'Published version headers are immutable');
select throws_ok($$update public.selection_publications set id=gen_random_uuid()$$,'23514',null,'Published identity cannot be replaced by trusted SQL');
select throws_ok($$update public.selection_publications set published_by=null$$,'23514',null,'Publisher cannot be anonymized while the member still exists');
select throws_ok($$update public.selection_publications set published_at=now()+interval '1 day'$$,'23514',null,'Published timestamp cannot be rewritten');
select throws_ok($$delete from public.selection_publication_members$$,'23514',null,'Snapshot content cannot be independently deleted');
create function pg_temp.reject_selection_audit() returns trigger language plpgsql as $$begin if new.event_type='selection_published' then raise exception 'Injected audit failure'; end if; return new; end;$$;
create trigger inject_publication_failure before insert on public.audit_events for each row execute function pg_temp.reject_selection_audit();
set local role authenticated;
select throws_ok($$select public.publish_selection((select id from sessions_fixture))$$,'P0001','Injected audit failure','Unexpected publication failure rolls back the transaction');
select is((select max(version) from public.selection_publications),1,'Failed publication creates no partial header/version');
select is((select count(*) from public.selection_publication_members),3::bigint,'Failed publication creates no partial snapshot content');
select is((select count(*) from public.selection_drafts),1::bigint,'Failed publication preserves the working draft');
reset role;
drop trigger inject_publication_failure on public.audit_events;
set local role authenticated;
select lives_ok($$select public.publish_selection((select id from sessions_fixture))$$,'Republish succeeds after failure');
select is((select max(version) from public.selection_publications),2,'Republish creates version two');
select is((select min(publication_version) from public.get_current_selection((select id from sessions_fixture))),2,'Live states and version are read from the same database snapshot');
select is((select count(*) from public.selection_publication_members pm join public.selection_publications pub on pub.id=pm.publication_id where pub.version=1 and pm.state='selected'),2::bigint,'Version one is unchanged after republish');
select lives_ok($$select public.set_draft_selection((select id from sessions_fixture),(select id from members_fixture where email='selection.member@example.test'),'declined')$$,'Admin prepares a later declined decision');
select lives_ok($$select public.discard_selection_draft((select id from sessions_fixture))$$,'Draft can be abandoned');
select is((select count(*) from public.get_current_selection((select id from sessions_fixture)) where state='selected'),2::bigint,'Discard does not alter published selection');
select public.set_draft_selection((select id from sessions_fixture),(select id from members_fixture where email='selection.member@example.test'),'declined');
select public.publish_selection((select id from sessions_fixture));
select is((select state from public.get_current_selection((select id from sessions_fixture)) where member_id=(select id from members_fixture where email='selection.member@example.test')),'declined','Latest publication becomes visible');
select throws_ok($$update public.selection_publication_members set state='selected'$$,'42501',null,'Browser cannot write snapshot rows directly');
select throws_ok($$select email from public.get_current_selection((select id from sessions_fixture))$$,'42703',null,'Selection projection reveals no private profile email');
select lives_ok($$select public.delete_session((select id from sessions_fixture))$$,'Admin session deletion can cascade the complete publication history');
select is((select count(*) from public.selection_publications),0::bigint,'Session deletion removes its publications');
reset role;
select * from finish();
rollback;
