begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('51000000-0000-4000-8000-000000000001','preview.member@example.test',now()),
('51000000-0000-4000-8000-000000000002','preview.admin@example.test',now()),
('51000000-0000-4000-8000-000000000003','preview.other@example.test',now());
select public.provision_member('51000000-0000-4000-8000-000000000001','Alice','Fictif');
select public.provision_member('51000000-0000-4000-8000-000000000002','Bob','Fictif');
select public.provision_member('51000000-0000-4000-8000-000000000003','Claire','Fictif');
update public.members set role='admin' where email='preview.admin@example.test';
create temp table people as select id,email from public.members where email like 'preview.%';
create temp table scenario(id uuid,preview jsonb);
grant select on people to authenticated; grant select,insert,update on scenario to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','51000000-0000-4000-8000-000000000002',true);
insert into scenario(id) select public.save_session('2030-10-01','21:00','22:00','Comparaison','','','',1,true,false,false);
select public.set_session_rsvp((select id from scenario),'yes',(select id from people where email='preview.member@example.test'));
select public.set_session_rsvp((select id from scenario),'yes',(select id from people where email='preview.other@example.test'));
select public.set_draft_selection((select id from scenario),(select id from people where email='preview.member@example.test'),'selected');
update scenario set preview=public.get_selection_publish_preview(id);
select is((select preview->>'publication_version' from scenario),'0','Preview explicitly identifies first publication');
select is((select count(*) from public.selection_publications),0::bigint,'Preview makes no publication/write');
select is((select count(*) from jsonb_array_elements((select preview->'rows' from scenario)) r where r->>'draft_state'='selected'),1::bigint,'Preview contains one selected candidate');
select set_config('request.jwt.claim.sub','51000000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.get_selection_publish_preview((select id from scenario))$$,'42501',null,'Member cannot retrieve admin comparison');
select throws_ok($$select public.publish_selection_checked((select id from scenario),(select preview->>'fingerprint' from scenario))$$,'42501',null,'Member cannot confirm publication');
select set_config('request.jwt.claim.sub','51000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.publish_selection_checked((select id from scenario),null)$$,'40001','SELECTION_PREVIEW_STALE','Missing comparison rejected before writes');
select lives_ok($$select public.publish_selection_checked((select id from scenario),(select preview->>'fingerprint' from scenario))$$,'Fresh preview publishes through existing RPC');
select is((select max(version) from public.selection_publications),1,'First checked publication creates one version');
select is((select count(*) from public.audit_events where event_type='selection_published'),1::bigint,'Existing publication audit retained');
update scenario set preview=public.get_selection_publish_preview(id);
select public.set_draft_selection((select id from scenario),(select id from people where email='preview.member@example.test'),'waiting');
select public.set_draft_selection((select id from scenario),(select id from people where email='preview.other@example.test'),'selected');
select throws_ok($$select public.publish_selection_checked((select id from scenario),(select preview->>'fingerprint' from scenario))$$,'40001','SELECTION_PREVIEW_STALE','An equal-count swap invalidates earlier comparison');
select is((select max(version) from public.selection_publications),1,'Stale confirmation leaves published version unchanged');
update scenario set preview=public.get_selection_publish_preview(id);
select is((select count(*) from jsonb_array_elements((select preview->'rows' from scenario)) r where r->>'published_state'='selected' and r->>'draft_state'='waiting'),1::bigint,'Nominal comparison contains removed confirmed person');
select is((select count(*) from jsonb_array_elements((select preview->'rows' from scenario)) r where r->>'published_state'='waiting' and r->>'draft_state'='selected'),1::bigint,'Nominal comparison contains added confirmed person');
select public.set_payment_status((select id from scenario),(select id from people where email='preview.other@example.test'),'paid');
select lives_ok($$select public.publish_selection_checked((select id from scenario),(select preview->>'fingerprint' from scenario))$$,'Unrelated payment change does not invalidate publication comparison');
select throws_ok($$select public.publish_selection_checked((select id from scenario),(select preview->>'fingerprint' from scenario))$$,'40001','SELECTION_PREVIEW_STALE','Replay/double publication is rejected');
update scenario set preview=public.get_selection_publish_preview(id);
select public.set_session_rsvp((select id from scenario),'no',(select id from people where email='preview.other@example.test'),false,true);
select throws_ok($$select public.publish_selection_checked((select id from scenario),(select preview->>'fingerprint' from scenario))$$,'40001','SELECTION_PREVIEW_STALE','Withdrawal invalidates comparison without changing immutable publication');
update scenario set preview=public.get_selection_publish_preview(id);
select is((select count(*) from jsonb_array_elements((select preview->'rows' from scenario)) r where r->>'published_state'='selected'),0::bigint,'Comparison uses effective publication after withdrawal');
select public.save_session('2030-10-01','21:00','22:00','Comparaison','','','',2,true,false,false,(select id from scenario));
select throws_ok($$select public.publish_selection_checked((select id from scenario),(select preview->>'fingerprint' from scenario))$$,'40001','SELECTION_PREVIEW_STALE','Capacity change requires a new comparison');
reset role;
select * from finish(); rollback;
