begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('20000000-0000-4000-8000-000000000001','sessions.member@example.test',now()),
('20000000-0000-4000-8000-000000000002','sessions.admin@example.test',now()),
('20000000-0000-4000-8000-000000000003','sessions.other@example.test',now()),
('20000000-0000-4000-8000-000000000004','sessions.unlinked@example.test',now());
select public.provision_member('20000000-0000-4000-8000-000000000001','Membre','Test');
select public.provision_member('20000000-0000-4000-8000-000000000002','Admin','Test');
select public.provision_member('20000000-0000-4000-8000-000000000003','Autre','Test');
update public.members set role='admin' where email='sessions.admin@example.test';
update public.members set caci_expiry_date='2027-01-01' where email='sessions.member@example.test';
create temp table fixture as select id,email from public.members where email like 'sessions.%';
create temp table session_fixture(id uuid);
grant select on fixture to authenticated;
grant select,insert on session_fixture to authenticated;
set local role anon;
select throws_ok($$select * from public.sessions$$,'42501',null,'Anonymous sessions are denied');
select throws_ok($$select public.get_session_responses(gen_random_uuid())$$,'42501',null,'Anonymous response projection is denied');
reset role;
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000002',true);
insert into session_fixture select public.save_session('2027-02-01','21:00','22:00','Fosse','Piscine','','',1,true,true,false);
select is((select count(*) from public.sessions),1::bigint,'Admin creates a session');
select ok((select school_holiday from public.sessions),'Manual holiday marking is shared');
select throws_ok($$select public.save_session('2027-02-01','22:00','21:00','Fosse','','','',1,true,false,false)$$,'23514',null,'End must follow start the same day');
select throws_ok($$select public.save_session('2027-02-01','21:00','22:00','Fosse','','','',0,true,false,false)$$,'23514',null,'Capacity cannot be zero');
select throws_ok($$select public.save_session('infinity','21:00','22:00','Fosse','','','',20,true,false,false)$$,'23514',null,'Dates must be finite');
select lives_ok($$select public.set_session_rsvp((select id from session_fixture),'yes')$$,'Administrator can register without advisory confirmation');
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.save_session('2027-02-01','21:00','22:00','Fosse','','','',1,true,false,false)$$,'42501',null,'Member cannot create sessions');
select throws_ok($$update public.sessions set capacity=10$$,'42501',null,'Member cannot bypass session RPC');
select throws_ok($$select public.delete_session((select id from session_fixture))$$,'42501',null,'Member cannot delete sessions');
select throws_ok($$select public.set_session_rsvp((select id from session_fixture),'yes')$$,'P0001','CACI_WARNING','Warning uses session date although CACI was valid before then');
select lives_ok($$select public.set_session_rsvp((select id from session_fixture),'yes',null,true)$$,'Confirmation allows expired-on-session-day CACI');
select is((select rsvp::text from public.session_participations),'yes','Member reads their own response');
select is((select count(*) from public.session_participations),1::bigint,'Private operational rows stay self-only');
select is((select count(*) from public.get_session_responses((select id from session_fixture)) where rsvp='yes'),2::bigint,'Yes responses exceed capacity one');
select throws_ok($$select email from public.get_session_responses((select id from session_fixture))$$,'42703',null,'Response projection exposes no private email');
select throws_ok($$select caci_expiry_date from public.get_session_responses((select id from session_fixture))$$,'42703',null,'Response projection exposes no private CACI');
select throws_ok($$select payment_status from public.get_session_responses((select id from session_fixture))$$,'42703',null,'Response projection exposes no private payment');
select throws_ok($$update public.session_participations set payment_status='paid'$$,'42501',null,'Members cannot write private operational columns');
select throws_ok($$select public.set_session_rsvp((select id from session_fixture),'no',(select id from fixture where email='sessions.admin@example.test'))$$,'42501',null,'Member cannot change another response');
select lives_ok($$select public.set_session_rsvp((select id from session_fixture),'maybe')$$,'Member changes response to Maybe');
select is((select rsvp_revision from public.session_participations),2,'Revision records changed response for future snapshot integrity');
select lives_ok($$select public.set_session_rsvp((select id from session_fixture),'no')$$,'Member changes response to No');
select is((select count(*) from public.get_session_responses((select id from session_fixture)) where rsvp in('yes','maybe')),1::bigint,'Participants projection can filter No out');
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000003',true);
select throws_ok($$select public.set_session_rsvp((select id from session_fixture),'yes')$$,'P0001','CACI_WARNING','Missing CACI also warns');
select lives_ok($$select public.set_session_rsvp((select id from session_fixture),'yes',null,true)$$,'Missing CACI is advisory');
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000002',true);
select lives_ok($$select public.save_session('2027-02-01','21:00','22:00','Fosse','','','',1,false,true,false,(select id from session_fixture))$$,'Admin closes registration without selecting anyone');
select lives_ok($$select public.set_session_rsvp((select id from session_fixture),'maybe',(select id from fixture where email='sessions.member@example.test'))$$,'Admin corrects another response while registration closed');
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000001',true);
select throws_ok($$select public.set_session_rsvp((select id from session_fixture),'yes',null,true)$$,'22023','Inscriptions fermées.','Member cannot register when registration closed');
select lives_ok($$select public.set_session_rsvp((select id from session_fixture),'no')$$,'Member may withdraw when registration closed');
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000004',true);
select is((select count(*) from public.sessions),0::bigint,'Authenticated account without membership cannot read calendar');
select throws_ok($$select public.get_session_responses((select id from session_fixture))$$,'42501',null,'Unlinked account cannot browse responses');
reset role;
update public.sessions set status='closed',registration_open=false;
set local role authenticated;
select set_config('request.jwt.claim.sub','20000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.set_session_rsvp((select id from session_fixture),'no')$$,'22023',null,'Closed bilan prevents response mutations even for administrator');
reset role;
update public.members set role='member' where email='sessions.admin@example.test';
set local role authenticated;
select throws_ok($$select public.delete_session((select id from session_fixture))$$,'42501',null,'Revoked administrator cannot delete with an existing identity token');
select throws_ok($$select public.save_session('2027-02-01','21:00','22:00','Fosse','','','',1,false,true,false,(select id from session_fixture))$$,'42501',null,'Revoked administrator cannot update a session');
select is((select count(*) from public.session_participations),1::bigint,'Revocation immediately removes access to other private participation rows');
reset role;
update public.members set role='admin' where email='sessions.admin@example.test';
set local role authenticated;
select lives_ok($$select public.delete_session((select id from session_fixture))$$,'Admin deletes the session');
select is((select count(*) from public.session_participations),0::bigint,'Session deletion cascades participations');
select is((select count(*) from public.audit_events where event_type='session_deleted' and payload->>'session_id'=(select id::text from session_fixture)),1::bigint,'Session deletion audit survives');
select is((select payload->>'session_id' from public.audit_events where event_type='session_deleted' and payload->>'session_id'=(select id::text from session_fixture)),(select id::text from session_fixture),'Deletion audit preserves original session identity');
reset role;
select * from finish();
rollback;
