begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,email,email_confirmed_at) values
('80000000-0000-4000-8000-000000000001','review.driver@example.test',now()),
('80000000-0000-4000-8000-000000000002','review.member@example.test',now()),
('80000000-0000-4000-8000-000000000003','review.other@example.test',now());
select public.provision_member('80000000-0000-4000-8000-000000000001','Conducteur','Revue');
select public.provision_member('80000000-0000-4000-8000-000000000002','Passager','Revue');
select public.provision_member('80000000-0000-4000-8000-000000000003','Autre','Revue');
update public.members set role='admin' where email='review.driver@example.test';
create temp table review_members as select id,email from public.members where email like 'review.%';
create temp table review_session(id uuid);
grant select on review_members to authenticated;
grant select,insert on review_session to authenticated;
set local role authenticated;
select set_config('request.jwt.claim.sub','80000000-0000-4000-8000-000000000001',true);
insert into review_session select public.save_session('2030-10-01','21:00','22:00','Revue','','','',2,true,false,false);
select public.set_session_rsvp((select id from review_session),'yes');
select public.set_session_rsvp((select id from review_session),'yes',(select id from review_members where email='review.member@example.test'));
select public.set_payment_status((select id from review_session),(select id from review_members where email='review.other@example.test'),'paid');
select public.set_draft_selection((select id from review_session),id,'selected') from review_members where email<>'review.other@example.test';
select ok((select not selected and passengers=0 from public.get_rsvp_change_consequences((select id from review_session))),'Initial preflight has no published place or passengers');
select public.publish_selection((select id from review_session));
select public.set_draft_palanquee((select id from review_session),id,1,false) from review_members where email<>'review.other@example.test';
select public.publish_palanquees((select id from review_session));
select public.offer_car((select id from review_session),1,'Parking','');
select set_config('request.jwt.claim.sub','80000000-0000-4000-8000-000000000002',true);
select public.join_car((select id from review_session),(select id from public.car_offers where session_id=(select id from review_session)));
select throws_ok($$select public.get_rsvp_change_consequences((select id from review_session),(select id from review_members where email='review.driver@example.test'))$$,'42501',null,'Member cannot inspect another RSVP correction');
select throws_ok($$select public.get_admin_session_responses((select id from review_session))$$,'42501',null,'Full administrative responses are role protected');
select is((select count(*) from public.get_session_responses((select id from review_session))),2::bigint,'Member projection excludes unanswered payment-only row');
select set_config('request.jwt.claim.sub','80000000-0000-4000-8000-000000000001',true);
select ok((select selected and passengers=1 from public.get_rsvp_change_consequences((select id from review_session))),'Warning describes confirmed place and passenger displacement');
select throws_ok($$select public.set_session_rsvp((select id from review_session),'maybe')$$,'P0001','RSVP_WITHDRAWAL_WARNING','Maybe cannot silently release selection/occupied car');
select throws_ok($$select public.set_session_rsvp((select id from review_session),'no')$$,'P0001','RSVP_WITHDRAWAL_WARNING','No cannot silently release selection/occupied car');
select is((select rsvp::text from public.session_participations where session_id=(select id from review_session) and member_id=public.current_member_id()),'yes','Unconfirmed change preserves response');
select is((select occupied from public.get_car_offers((select id from review_session))),1::bigint,'Unconfirmed change preserves passenger seat');
select throws_ok($$select public.set_session_rsvp((select id from review_session),'no',(select id from review_members where email='review.member@example.test'))$$,'P0001','RSVP_WITHDRAWAL_WARNING','Admin correction also requires place-loss confirmation');
select lives_ok($$select public.set_session_rsvp((select id from review_session),'no',null,false,true)$$,'Explicit confirmation uses transactional withdrawal');
select is((select count(*) from public.get_car_offers((select id from review_session))),0::bigint,'Confirmed withdrawal removes car');
select is((select rsvp::text from public.session_participations where session_id=(select id from review_session) and member_id=(select id from review_members where email='review.member@example.test')),'yes','Displaced passenger stays registered');
select is((select mode::text from public.get_session_transport((select id from review_session)) where member_id=(select id from review_members where email='review.member@example.test')),'needs','Displaced passenger needs a new trip');
select is((select count(*) from public.get_admin_session_responses((select id from review_session))),3::bigint,'Administrator projection retains No and unanswered corrections');
select set_config('request.jwt.claim.sub','80000000-0000-4000-8000-000000000002',true);
select is((select count(*) from public.get_session_responses((select id from review_session))),1::bigint,'Other No response is absent at the API boundary');
select is((select count(*) from public.get_current_selection((select id from review_session))),1::bigint,'Selection projection does not restore No/unanswered identities');
select is((select count(*) from public.selection_publication_members where member_id=(select id from review_members where email='review.driver@example.test')),0::bigint,'Direct selection history cannot bypass response minimization');
select is((select count(*) from public.palanquee_publication_members where member_id=(select id from review_members where email='review.driver@example.test')),0::bigint,'Direct group history cannot bypass response minimization');
select throws_ok($$select caci_expiry_date from public.get_admin_session_responses((select id from review_session))$$,'42703',null,'Administrative response projection still has no CACI');
select set_config('request.jwt.claim.sub','80000000-0000-4000-8000-000000000001',true);
reset role;
update public.members set role='member' where email='review.driver@example.test';
set local role authenticated;
select is((select state from public.get_current_selection((select id from review_session)) where member_id=public.current_member_id()),'withdrawn','Member retains own withdrawal status');
select is((select count(*) from public.selection_publication_members where member_id=public.current_member_id()),1::bigint,'Own historical selection remains readable and immutable');
select throws_ok($$select public.get_admin_session_responses((select id from review_session))$$,'42501',null,'Revoked admin cannot use broad projection with old identity');
reset role;
set local role anon;
select throws_ok($$select public.get_rsvp_change_consequences(gen_random_uuid())$$,'42501',null,'Anonymous consequence inspection denied');
select throws_ok($$select public.get_admin_session_responses(gen_random_uuid())$$,'42501',null,'Anonymous broad projection denied');
reset role;
select * from finish();
rollback;
