begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
create temp table seed_test(auth_ids uuid[],members uuid[],sessions uuid[],tester jsonb,events bigint);
grant select on seed_test to authenticated,service_role;
insert into auth.users(id,email,email_confirmed_at,raw_app_meta_data)
select ('55000000-0000-0000-0000-'||lpad(i::text,12,'0'))::uuid,
  'plongeur-'||lpad(i::text,2,'0')||'@ifosse-seed.invalid',now(),'{"ifosse_staging_seed":"ifosse-staging-v1"}'::jsonb from generate_series(1,30) i;
insert into auth.users(id,email,email_confirmed_at) values('55000000-0000-0000-0001-000000000001','manual-tester@example.test',now());
select public.provision_member('55000000-0000-0000-0001-000000000001','Manuel','Testeur');
update public.members set role='president',current_level='E3',caci_expiry_date=current_date+200 where email='manual-tester@example.test';
insert into seed_test(auth_ids,tester) select array_agg(id order by email),(select to_jsonb(m) from public.members m where email='manual-tester@example.test') from auth.users where email like 'plongeur-%@ifosse-seed.invalid';
set local role anon;
select throws_ok($$select public.staging_seed_status()$$,'42501',null,'Anonymous cannot inspect operator seed');
select throws_ok($$select public.apply_staging_seed(null)$$,'42501',null,'Anonymous cannot seed');
reset role;
set local role authenticated;
select throws_ok($$select public.apply_staging_seed(null)$$,'42501',null,'Even browser admins cannot seed');
reset role;
set local role service_role;
select set_config('request.jwt.claims','{"role":"service_role","ref":"production"}',true);
select throws_ok($$select public.apply_staging_seed((select auth_ids from seed_test))$$,'42501',null,'Production project JWT rejected before writes');
select is((select count(*) from public.sessions),0::bigint,'Wrong target creates no sessions');
select set_config('request.jwt.claims','{"role":"service_role","ref":"btpojwwwsxrepsehmxbm"}',true);
select is((public.staging_seed_status()->>'initialized')::boolean,false,'Preflight identifies first initialization');
select is((select count(*) from public.members),1::bigint,'Preflight creates no profiles');
select throws_ok($$select public.apply_staging_seed(array['55000000-0000-0000-0001-000000000001']::uuid[])$$,'22023',null,'Arbitrary tester IDs rejected');
reset role;
update auth.users set raw_app_meta_data='{}' where email='plongeur-30@ifosse-seed.invalid';
set local role service_role;
select throws_ok($$select public.staging_seed_status()$$,'23505',null,'Unowned Auth collision refused, never adopted');
reset role;
update auth.users set raw_app_meta_data='{"ifosse_staging_seed":"ifosse-staging-v1"}' where email='plongeur-30@ifosse-seed.invalid';
insert into public.members(first_name,last_name,email) values('Collision','Manuelle','plongeur-30@ifosse-seed.invalid');
set local role service_role;
select throws_ok($$select public.apply_staging_seed((select auth_ids from seed_test))$$,'23505',null,'Existing same-email profile refused before any seed writes');
reset role;
delete from public.members where email='plongeur-30@ifosse-seed.invalid';
create function public.seed_test_fail_late() returns trigger language plpgsql as $$begin
  if new.title like '%Inscriptions sans publication' then raise exception 'late fixture failure'; end if;
  return new;
end$$;
create trigger seed_test_fail_late before insert on public.sessions for each row execute function public.seed_test_fail_late();
set local role service_role;
select throws_ok($$select public.apply_staging_seed((select auth_ids from seed_test))$$,'P0001','late fixture failure','Late business failure rolls back entire dataset');
select is((select count(*) from public.sessions),0::bigint,'Late failure leaves no sessions');
select is((select count(*) from public.members),1::bigint,'Late failure leaves no synthetic profiles or promotions');
reset role;
drop trigger seed_test_fail_late on public.sessions;
drop function public.seed_test_fail_late();
set local role service_role;
select lives_ok($$select public.apply_staging_seed((select auth_ids from seed_test))$$,'Valid owned staging identities populate via business RPCs');
select is(auth.role(),'service_role','Seed restores caller role');
select is(auth.jwt()->>'ref','btpojwwwsxrepsehmxbm','Seed restores caller project claims');
reset role;
update seed_test set members=(select member_ids from public.staging_seed_runs),sessions=(select session_ids from public.staging_seed_runs),events=(select count(*) from public.audit_events);
select is((select to_jsonb(m) from public.members m where email='manual-tester@example.test'),(select tester from seed_test),'Manual tester profile, role and timestamps exactly preserved');
select is((select count(*) from public.members),31::bigint,'30 fixtures coexist with manual tester');
select is((select count(*) from public.members where role='president'),1::bigint,'No seed president and existing presidency preserved');
select is((select count(*) from public.sessions),7::bigint,'Seven synthetic sessions');
select is((select count(*) from public.session_participations),210::bigint,'Seven coherent RSVP mixes for 30 members');
select is((select count(*) from public.session_participations where session_id=(select sessions[4] from seed_test) and rsvp='yes'),22::bigint,'22 volunteers allowed in 20-place session');
select is((select capacity from public.sessions where id=(select sessions[4] from seed_test)),20,'Oversubscribed capacity stays 20');
select is((select count(*) from public.current_selected_ids((select sessions[4] from seed_test))),20::bigint,'Published effective selection respects capacity');
select ok(exists(select 1 from public.selection_draft where session_id=(select sessions[4] from seed_test) and member_id=(select members[21] from seed_test) and state='selected'),'Private draft adds waiting member');
select ok(not exists(select 1 from public.current_selected_ids((select sessions[4] from seed_test)) where member_id=(select members[21] from seed_test)),'Private change does not leak to publication');
select is((select count(*) from public.selection_publications where session_id=(select sessions[7] from seed_test)),0::bigint,'Unpublished scenario has no snapshot');
select is((select max(version) from public.selection_publications where session_id=(select sessions[6] from seed_test)),2,'Republication scenario');
select is((select count(*) from public.car_offers),3::bigint,'Multiple remaining cars');
select is((select count(*) from public.car_passengers),7::bigint,'Seven passengers');
select ok(exists(select 1 from public.car_offers c where passenger_capacity=(select count(*) from public.car_passengers where car_offer_id=c.id)),'Full car');
select ok(exists(select 1 from public.car_offers c where passenger_capacity-1=(select count(*) from public.car_passengers where car_offer_id=c.id)),'Nearly full car');
select is((select count(*) from public.session_participations where session_id=(select sessions[5] from seed_test) and member_id in((select members[19] from seed_test),(select members[20] from seed_test)) and rsvp='yes' and transport_mode='needs'),2::bigint,'Driver withdrawal retains volunteers needing reassignment');
select is((select count(*) from public.palanquee_publication_members),20::bigint,'Twenty published assignments');
select is((select count(*) from public.sessions where status='closed'),3::bigint,'Three validated historical bilans');
select is((select count(*) from public.session_participations where attendance_status='dived'),45::bigint,'Attendance history includes actual divers');
select is((select count(distinct payment_status) from public.session_participations),3::bigint,'All payment states represented');
select is((select count(*) from public.members where id in(select unnest(members) from seed_test) and caci_expiry_date is null),7::bigint,'Missing CACI is represented');
select ok(exists(select 1 from public.members where id in(select unnest(members) from seed_test) and caci_expiry_date<current_date),'Expired CACI exists');
select ok(exists(select 1 from public.members where id in(select unnest(members) from seed_test) and caci_expiry_date between current_date and current_date+60),'Soon-expiring CACI exists');
select ok(exists(select 1 from public.members where id in(select unnest(members) from seed_test) and caci_expiry_date>current_date+60),'Valid CACI exists');
set local role authenticated;
select set_config('request.jwt.claims','{"role":"authenticated","sub":"55000000-0000-0000-0001-000000000001"}',true);
select is((select count(*) from public.get_current_selection((select sessions[5] from seed_test)) where state='withdrawn'),1::bigint,'Admin sees effective withdrawal');
select is((select count(*) from public.get_current_selection((select sessions[4] from seed_test)) where state='declined'),1::bigint,'Not-selected volunteer is visible');
select ok(exists(select 1 from public.get_season_counts(extract(year from current_date)::integer-case when extract(month from current_date)<9 then 1 else 0 end) where completed_count>0),'Current season participation counters nonempty');
select set_config('request.jwt.claims','{"role":"authenticated","sub":"55000000-0000-0000-0000-000000000004"}',true);
select is((select count(*) from public.members),1::bigint,'Seed preserves ordinary member directory RLS');
select is((select count(*) from public.get_current_selection((select sessions[4] from seed_test)) where state='selected'),20::bigint,'Regular member sees effective published selection, not draft');
select is((select count(*) from public.get_current_palanquees((select sessions[4] from seed_test))),20::bigint,'Regular member sees published palanquées');
select throws_ok($$select * from public.staging_seed_runs$$,'42501',null,'Ownership registry inaccessible to browsers');
reset role;
select set_config('request.jwt.claims','{"role":"service_role","ref":"btpojwwwsxrepsehmxbm"}',true);
-- A manual change to a seed record must survive reruns too.
update public.sessions set notes='Correction du testeur conservée' where id=(select sessions[4] from seed_test);
set local role service_role;
select is((public.apply_staging_seed((select auth_ids from seed_test))->>'writes')::integer,0,'Retry is a no-op');
reset role;
select is((select count(*) from public.audit_events),(select events from seed_test),'Retry creates no extra audit events');
select is((select notes from public.sessions where id=(select sessions[4] from seed_test)),'Correction du testeur conservée','Retry preserves organizer edits');
select is((select count(*) from public.sessions),7::bigint,'Retry never duplicates sessions');
select is((select to_jsonb(m) from public.members m where email='manual-tester@example.test'),(select tester from seed_test),'Retry leaves non-seed member untouched');
-- Missing provenance targets block rather than silently recreating user work.
delete from public.sessions where id=(select sessions[7] from seed_test);
set local role service_role;
select throws_ok($$select public.staging_seed_status()$$,'22023',null,'Deleted seed session requires inspection, no destructive reset');
reset role;
select * from finish();
rollback;
