import { expect, test } from '@playwright/test'
import { createMemberFixture, fixtureClient, makeFixtureAdmin, openConfirmation, removeMemberFixture, requestMagicLink } from './helpers/local-supabase.js'
import { createSession, testSessionDate } from './helpers/sessions.js'
import { formatDate } from '../src/lib/dates.js'

test('waiting-driver trips are provisional and car defaults stay explicitly optional', async ({ page, browser }) => {
  test.setTimeout(120000)
  const driver = await createMemberFixture(); const passenger = await createMemberFixture()
  makeFixtureAdmin(driver)
  await page.setViewportSize({ width: 390, height: 844 })
  const context = await browser.newContext({ viewport: { width: 390, height: 844 } }); const other = await context.newPage()
  let client: Awaited<ReturnType<typeof fixtureClient>> | undefined; let id: string | undefined
  try {
    for (const [device, fixture] of [[page, driver], [other, passenger]] as const) {
      await openConfirmation(device, await requestMagicLink(device, fixture))
      await device.getByRole('button', { name: 'Se connecter', exact: true }).click()
      await expect(device.getByRole('heading', { name: 'Les séances', exact: true })).toBeVisible()
    }
    await page.getByRole('button', { name: 'Mon profil', exact: true }).click()
    await page.getByLabel('Téléphone', { exact: true }).fill('0699999999') // Unsaved sibling form must survive opt-in refresh.
    await page.getByRole('button', { name: 'Séances', exact: true }).click()
    client = await fixtureClient(driver)
    id = await createSession(client, `Voiture provisoire ${driver.firstName}`)
    for (const fixture of [driver, passenger]) {
      expect((await client.rpc('set_session_rsvp', { p_session_id: id, p_member_id: fixture.memberId, p_rsvp: 'yes' })).error).toBeNull()
      expect((await client.rpc('set_member_caci', { p_member_id: fixture.memberId, p_expiry_date: '2099-12-31' })).error).toBeNull()
    }
    expect((await client.rpc('set_payment_status', { p_session_id: id, p_member_id: passenger.memberId, p_status: 'paid' })).error).toBeNull()
    expect((await client.rpc('set_draft_selection', { p_session_id: id, p_member_id: passenger.memberId, p_state: 'selected' })).error).toBeNull()
    expect((await client.rpc('publish_selection', { p_session_id: id })).error).toBeNull()
    for (const device of [page, other]) {
      const open = device.getByRole('button', { name: new RegExp(`séance du ${formatDate(testSessionDate)}`) })
      await expect(open).toBeVisible({ timeout: 12000 }); await open.click()
      await device.getByRole('tab', { name: 'Covoiturage', exact: true }).click()
    }
    const panel = page.locator('.carpool'); const memberPanel = other.locator('.carpool')
    await expect(panel.getByLabel('Places passagers proposées')).toHaveCount(0)
    await panel.getByRole('button', { name: 'Proposer une voiture', exact: true }).click()
    await panel.getByLabel('Places passagers proposées').fill('1')
    await panel.getByLabel('Point de rendez-vous', { exact: true }).fill('Voiture empruntée')
    await panel.getByRole('button', { name: 'Enregistrer ma voiture', exact: true }).click()
    await panel.getByRole('button', { name: 'Garder une offre ponctuelle', exact: true }).click()
    expect((await client.from('members').select('has_usual_car').eq('id', driver.memberId).single()).data?.has_usual_car).toBe(false)
    const join = memberPanel.getByRole('button', { name: `Rejoindre la voiture de ${driver.firstName} Fictif` })
    await expect(join).toBeVisible({ timeout: 12000 }); await join.click()
    const provisional = memberPanel.getByText('Trajet provisoire : le conducteur n’est pas confirmé dans la sélection publiée.', { exact: true })
    await expect(provisional).toBeVisible()
    await expect(memberPanel.getByText('Conducteur en attente de confirmation · Trajet provisoire.', { exact: true })).toBeVisible()
    await page.getByRole('tab', { name: 'Gestion', exact: true }).click()
    const readiness = page.locator('.readiness').filter({ has: page.getByRole('combobox', { name: `Paiement de ${passenger.firstName} Fictif`, exact: true }) })
    await expect(readiness).toContainText('3/4 points prêts')
    await expect(readiness).toContainText('Provisoire : conducteur non confirmé')
    const driverSelection = page.getByRole('combobox', { name: `Sélection de ${driver.firstName} Fictif`, exact: true })
    await driverSelection.selectOption('selected')
    await expect(readiness).toContainText('Brouillon prêt à publier')
    await expect(readiness).toContainText('Base du récapitulatif : brouillon privé, à publier.')
    await expect(provisional).toBeVisible()
    await page.getByRole('button', { name: 'Publier la sélection', exact: true }).click()
    await page.getByRole('button', { name: 'Confirmer la publication', exact: true }).click()
    await expect(provisional).toHaveCount(0, { timeout: 12000 })
    await expect(memberPanel.getByText('Conducteur confirmé dans la sélection publiée.', { exact: true })).toBeVisible()
    await page.getByRole('tab', { name: 'Covoiturage', exact: true }).click()
    await panel.getByRole('button', { name: 'Retirer ma voiture', exact: true }).click()
    await panel.getByRole('button', { name: 'Confirmer le retrait de ma voiture', exact: true }).click()
    await expect(memberPanel.getByText('Mon trajet : Je cherche un trajet', { exact: true })).toBeVisible({ timeout: 12000 })
    await panel.getByRole('button', { name: 'Proposer une voiture', exact: true }).click()
    await panel.getByLabel('Places passagers proposées').fill('2')
    await panel.getByLabel('Point de rendez-vous', { exact: true }).fill('Parking habituel')
    await panel.getByRole('button', { name: 'Enregistrer ma voiture', exact: true }).click()
    await panel.getByRole('button', { name: 'Mémoriser pour les prochaines séances', exact: true }).click()
    await expect(panel.getByText('Habitudes de covoiturage enregistrées.', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Mon profil', exact: true }).click()
    await expect(page.getByLabel('Téléphone', { exact: true })).toHaveValue('0699999999')
    await expect(page.getByLabel('J’ai habituellement une voiture disponible')).toBeChecked()
    await expect(page.getByLabel('Places passagers habituelles')).toHaveValue('2')
    await expect(page.getByLabel('Point de rendez-vous habituel')).toHaveValue('Parking habituel')
    await page.getByRole('button', { name: 'Séances', exact: true }).click()
    await panel.getByRole('button', { name: 'Modifier ma voiture', exact: true }).click()
    await panel.getByLabel('Places passagers proposées').fill('1')
    await panel.getByLabel('Point de rendez-vous', { exact: true }).fill('Autre voiture empruntée')
    await panel.getByRole('button', { name: 'Enregistrer ma voiture', exact: true }).click()
    await expect(panel.getByText('Voiture enregistrée pour cette séance.', { exact: true })).toBeVisible()
    await expect(panel.locator('.car-default-prompt')).toHaveCount(0)
    const stored = await client.from('members').select('usual_passenger_seats,usual_meeting_point,phone').eq('id', driver.memberId).single()
    expect(stored.data).toEqual({ usual_passenger_seats: 2, usual_meeting_point: 'Parking habituel', phone: null })
    await expect(join).toBeVisible({ timeout: 12000 }); await join.click()
    await expect(memberPanel.getByText('Mon trajet : Passager', { exact: true })).toBeVisible()
    await page.getByRole('tab', { name: 'Gestion', exact: true }).click()
    await driverSelection.selectOption('declined')
    await expect(readiness).toContainText('Provisoire : conducteur non confirmé')
    await expect(memberPanel.getByText('Mon trajet : Passager', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Publier la sélection', exact: true }).click()
    await page.getByRole('button', { name: 'Confirmer la publication', exact: true }).click()
    await expect(memberPanel.getByText('Mon trajet : Je cherche un trajet', { exact: true })).toBeVisible({ timeout: 12000 })
    expect((await client.from('session_participations').select('rsvp').eq('session_id', id).eq('member_id', passenger.memberId).single()).data?.rsvp).toBe('yes')
    expect(await other.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false)
    await other.screenshot({ path: 'test-results/carpool-review-mobile.png', fullPage: true })
  } finally {
    if (id && client) await client.rpc('delete_session', { p_session_id: id })
    await context.close(); await removeMemberFixture(passenger); await removeMemberFixture(driver)
  }
})
