import { expect, test } from '@playwright/test'
import { createMemberFixture, openConfirmation, removeMemberFixture, requestMagicLink } from './helpers/local-supabase.js'

test('header identity opens own profile by pointer and keyboard while logout stays separate', async ({ page }) => {
  const member=await createMemberFixture()
  try {
    await openConfirmation(page,await requestMagicLink(page,member))
    await page.getByRole('button',{name:'Se connecter',exact:true}).click()
    const identity=page.getByRole('button',{name:'Ouvrir mon profil',exact:true})
    await expect(identity).toBeVisible()
    for (const part of ['.avatar','strong','.identity-role']) {
      await identity.locator(part).click()
      await expect(page.getByRole('heading',{name:'Mon profil',exact:true})).toBeVisible()
      await expect(page.getByRole('button',{name:'Mon profil',exact:true})).toHaveAttribute('aria-current','page')
      await page.getByRole('button',{name:'Séances',exact:true}).click()
    }
    for (const key of ['Enter','Space']) {
      await page.keyboard.press('Shift+Tab') // From Séances, move back through the separate logout control.
      await expect(page.getByRole('button',{name:'Se déconnecter',exact:true})).toBeFocused()
      await page.keyboard.press('Shift+Tab')
      await expect(identity).toBeFocused()
      expect(await identity.evaluate(element=>getComputedStyle(element).outlineStyle)).not.toBe('none')
      await page.keyboard.press(key)
      await expect(page.getByRole('heading',{name:'Mon profil',exact:true})).toBeVisible()
      await page.getByRole('button',{name:'Séances',exact:true}).click()
    }
    await page.setViewportSize({width:390,height:844})
    await identity.click()
    await expect(page.getByRole('heading',{name:'Mon profil',exact:true})).toBeVisible()
    expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
    const logout=page.getByRole('button',{name:'Se déconnecter',exact:true})
    expect(await identity.locator('button').count()).toBe(0)
    await logout.click()
    const dialog=page.getByRole('dialog',{name:'Se déconnecter ?'})
    const cancel=dialog.getByRole('button',{name:'Annuler',exact:true})
    await expect(dialog).toBeVisible()
    await expect(cancel).toBeFocused()
    await expect(identity).toBeAttached()
    expect(await page.evaluate(()=>Object.keys(localStorage).some(key=>key.endsWith('-auth-token')))).toBe(true)
    expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
    await cancel.click()
    await expect(dialog).not.toBeVisible()
    await expect(logout).toBeFocused()
    await expect(identity).toBeVisible()
    await page.keyboard.press('Enter')
    await expect(cancel).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(dialog).not.toBeVisible()
    await expect(logout).toBeFocused()
    await expect(identity).toBeVisible()
    await page.keyboard.press('Space')
    await expect(cancel).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(dialog.getByRole('button',{name:'Se déconnecter',exact:true})).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(cancel).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await page.keyboard.press('Enter')
    await expect(page.getByLabel('Adresse email')).toBeVisible()
    await expect(identity).toHaveCount(0)
    expect(await page.evaluate(()=>Object.keys(localStorage).some(key=>key.endsWith('-auth-token')))).toBe(false)
  } finally { await removeMemberFixture(member) }
})
