import { expect, test } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import type { Page } from '@playwright/test'
import { createMemberFixture, fixtureClient, makeFixtureAdmin, openConfirmation, removeMemberFixture, requestMagicLink, serviceClient } from './helpers/local-supabase.js'
import { createSession, testSessionDate } from './helpers/sessions.js'
import { formatDate } from '../src/lib/dates.js'

async function layout(page: Page, name: string) {
  expect(new URL(page.url()).hash).toBe('')
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await expect.poll(() => page.locator('button:visible, input:visible:not([type=checkbox]), select:visible').evaluateAll(nodes => nodes.filter(node => node.getBoundingClientRect().height < 43).map(node => ({ tag: node.tagName, class: node.className, height: node.getBoundingClientRect().height })))).toEqual([])
  const section = name.startsWith('profile') ? '.usual-car' : name.startsWith('car-summary') ? '.own-car-summary' : '.directory li:has(form)'
  await page.locator(section).first().evaluate(element => window.scrollTo(0, element.getBoundingClientRect().top + scrollY - 100))
  await page.screenshot({ path: `test-results/ux-polish-${name}.png` })
}

test('directory CACI collapses only on success, updates date/status and retains conflict/permission recovery', async ({ page }) => {
  const admin = await createMemberFixture(); const member = await createMemberFixture()
  try {
    makeFixtureAdmin(admin)
    await openConfirmation(page, await requestMagicLink(page, admin))
    await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
    const client = await fixtureClient(admin)
    const caciNotifications = async () => {
      const result=await serviceClient().from('member_notifications').select('id',{count:'exact',head:true}).eq('member_id',member.memberId).eq('kind','caci_updated')
      expect(result.error).toBeNull();return result.count
    }
    await page.getByRole('button', { name: 'Administration', exact: true }).click()
    const row = page.locator('.directory li').filter({ has: page.getByRole('button', { name: `Modifier le CACI de ${member.firstName} Fictif`, exact: true }) })
    const toggle = row.getByRole('button', { name: /Modifier le CACI/ })
    const date = row.getByLabel('Fin de validité CACI')
    await toggle.click(); await date.fill('2099-12-31')
    await row.getByRole('button', { name: 'Enregistrer le CACI', exact: true }).click()
    await expect(date).toHaveCount(0)
    await expect(row).toContainText(`CACI Valide · valable jusqu’au ${formatDate('2099-12-31')}`)
    await expect(toggle).toHaveAttribute('aria-expanded', 'false')
    await expect(toggle).toBeFocused()
    await expect.poll(caciNotifications).toBe(1)
    await expect(page.getByText('Email non envoyé : destinataire exclu des notifications de cet environnement.',{exact:true})).toBeVisible()
    await mkdir('test-results/visual-acceptance',{recursive:true})
    for(const [name,width,height] of [['desktop',1440,900],['phone',390,844]] as const){
      await page.setViewportSize({width,height})
      await page.getByText('Email non envoyé : destinataire exclu des notifications de cet environnement.',{exact:true}).scrollIntoViewIfNeeded()
      expect(new URL(page.url()).hash).toBe('')
      expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
      await page.screenshot({path:`test-results/visual-acceptance/caci-notification-${name}.png`})
    }
    await page.setViewportSize({width:1440,height:900})
    // Saving the same date still collapses but must not reuse an old email receipt.
    await toggle.click()
    await row.getByRole('button',{name:'Enregistrer le CACI',exact:true}).click()
    await expect(date).toHaveCount(0)
    await expect.poll(caciNotifications).toBe(1)
    await expect(page.getByText('Email non envoyé : destinataire exclu des notifications de cet environnement.',{exact:true})).toHaveCount(0)
    await toggle.click(); await date.fill('2098-12-31')
    // Race a genuine server-side update between submit and its compare/write RPC.
    await page.route('**/rest/v1/rpc/set_member_caci_if_current', async route => {
      expect((await client.rpc('set_member_caci', { p_member_id: member.memberId, p_expiry_date: '2097-12-31' })).error).toBeNull()
      await route.continue()
    }, { times: 1 })
    await row.getByRole('button', { name: 'Enregistrer le CACI', exact: true }).click()
    await expect(row.getByText('Le CACI a été modifié ailleurs.', { exact: false })).toBeVisible()
    await expect(date).toHaveValue('2098-12-31')
    await expect(toggle).toHaveAttribute('aria-expanded', 'true')
    await expect.poll(caciNotifications).toBe(2) // The external change, not the rejected save.
    await row.getByRole('button', { name: 'Recharger la date enregistrée', exact: true }).click()
    await expect(date).toHaveValue('2097-12-31')
    // Inject a permission response to verify UI recovery without changing account permissions.
    await page.route('**/rest/v1/rpc/set_member_caci_if_current', route => route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ code: '42501', message: 'permission denied' }) }), { times: 1 })
    await date.fill('2096-12-31'); await row.getByRole('button', { name: 'Enregistrer le CACI', exact: true }).click()
    await expect(row.getByText('Vos droits ne permettent plus cette action. Actualisez votre accès.', { exact: true })).toBeVisible()
    await expect(date).toHaveValue('2096-12-31')
    await expect.poll(caciNotifications).toBe(2)
    await page.getByLabel('Rechercher un adhérent').fill('Aucun résultat fictif')
    await expect(page.getByText('Aucun adhérent ne correspond à ces critères.')).toBeVisible()
    await page.getByRole('button',{name:'Réinitialiser les filtres',exact:true}).click()
    await expect(date).toHaveValue('2096-12-31')
    await expect(date).toBeVisible()
    await layout(page, 'directory-desktop-error')
    await page.setViewportSize({ width: 390, height: 844 }); await layout(page, 'directory-phone-error')
    await row.getByRole('button', { name: 'Enregistrer le CACI', exact: true }).click()
    await expect(date).toHaveCount(0)
    await expect(row).toContainText(`valable jusqu’au ${formatDate('2096-12-31')}`)
    await expect.poll(caciNotifications).toBe(3)
  } finally { await removeMemberFixture(member); await removeMemberFixture(admin) }
})

test('usual car prefills only an explicit offer; session summary reopens, retains rejected edits and confirms occupied withdrawal', async ({ page }) => {
  test.setTimeout(60000)
  const admin = await createMemberFixture(); const driver = await createMemberFixture()
  const passengers = [await createMemberFixture(), await createMemberFixture()]
  makeFixtureAdmin(admin)
  const organizer = await fixtureClient(admin)
  let id: string | undefined
  try {
    await openConfirmation(page, await requestMagicLink(page, driver))
    await page.getByRole('button', { name: 'Se connecter', exact: true }).click()
    await page.getByRole('button', { name: 'Mon profil', exact: true }).click()
    const usual = page.getByRole('group', { name: 'Ma voiture habituelle', exact: true })
    await expect(usual).toContainText('ne créent aucune offre automatiquement')
    await usual.getByLabel('J’ai habituellement une voiture disponible').check()
    await usual.getByLabel('Places passagers habituelles').fill('2')
    await usual.getByLabel('Point de rendez-vous habituel').fill('Parking habituel')
    await expect(usual.getByLabel('Heure de départ')).toHaveCount(0)
    await expect(usual.getByLabel('Note pour les passagers')).toHaveCount(0)
    await page.getByRole('button', { name: 'Enregistrer mon profil', exact: true }).click()
    await expect(page.getByText('Profil enregistré.', { exact: true })).toBeVisible()
    await layout(page, 'profile-desktop')
    await page.setViewportSize({ width: 390, height: 844 }); await layout(page, 'profile-phone')
    id = await createSession(organizer, `UX voiture ${driver.firstName}`, 4)
    for (const person of [driver, ...passengers]) expect((await organizer.rpc('set_session_rsvp', { p_session_id: id, p_member_id: person.memberId, p_rsvp: 'yes' })).error).toBeNull()
    await page.getByRole('button', { name: 'Séances', exact: true }).click()
    await page.getByRole('button', { name: new RegExp(`séance du ${formatDate(testSessionDate)}`), exact: true }).click()
    await page.getByRole('tab', { name: 'Covoiturage', exact: true }).click()
    const panel = page.locator('.carpool')
    await expect(panel.getByLabel('Places passagers proposées')).toHaveCount(0)
    expect((await organizer.rpc('get_car_offers', { p_session_id: id })).data).toEqual([])
    await panel.getByRole('button', { name: 'Proposer une voiture', exact: true }).click()
    await expect(panel.getByLabel('Places passagers proposées')).toHaveValue('2')
    await expect(panel.getByLabel('Point de rendez-vous', { exact: true })).toHaveValue('Parking habituel')
    await panel.getByLabel('Heure de départ').fill('19:45')
    await panel.getByLabel('Note pour les passagers').fill('Note de cette séance')
    await panel.getByRole('button', { name: 'Enregistrer ma voiture', exact: true }).click()
    await expect(panel.getByLabel('Places passagers proposées')).toHaveCount(0)
    const summary = panel.getByRole('region', { name: 'Ma voiture', exact: true })
    await expect(summary).toContainText('2 places libres / 2 places passagers.')
    await expect(summary).toContainText('Parking habituel · départ 19:45')
    const cars = await organizer.rpc('get_car_offers', { p_session_id: id })
    for (const passenger of passengers) expect((await (await fixtureClient(passenger)).rpc('join_car', { p_session_id: id, p_car_offer_id: cars.data![0].id })).error).toBeNull()
    await page.evaluate(() => window.dispatchEvent(new Event('focus')))
    await expect(summary).toContainText('0 places libres / 2 places passagers.')
    for (const passenger of passengers) await expect(summary).toContainText(`${passenger.firstName} Fictif`)
    await layout(page, 'car-summary-phone')
    await summary.getByRole('button', { name: 'Modifier ma voiture', exact: true }).click()
    await expect(panel.getByLabel('Heure de départ')).toHaveValue('19:45')
    await expect(panel.getByLabel('Note pour les passagers')).toHaveValue('Note de cette séance')
    await panel.getByLabel('Places passagers proposées').fill('1')
    await panel.getByRole('button', { name: 'Enregistrer ma voiture', exact: true }).click()
    await expect(panel.getByRole('alert')).toHaveText('Le nombre de places ne peut pas être inférieur aux passagers déjà à bord.')
    await expect(panel.getByLabel('Places passagers proposées')).toHaveValue('1')
    await panel.getByLabel('Places passagers proposées').fill('3')
    await panel.getByLabel('Point de rendez-vous', { exact: true }).fill('Autre parking pour cette séance')
    await panel.getByRole('button', { name: 'Enregistrer ma voiture', exact: true }).click()
    await expect(panel.getByLabel('Places passagers proposées')).toHaveCount(0)
    await expect(summary.getByRole('button', { name: 'Modifier ma voiture', exact: true })).toBeFocused()
    await expect(summary).toContainText('1 place libre / 3 places passagers.')
    await expect(summary).toContainText('Autre parking pour cette séance')
    await page.setViewportSize({ width: 1440, height: 900 }); await layout(page, 'car-summary-desktop')
    await summary.getByRole('button', { name: 'Modifier ma voiture', exact: true }).click()
    await expect(panel.getByLabel('Places passagers proposées')).toHaveValue('3')
    await panel.getByRole('button', { name: 'Annuler la modification', exact: true }).click()
    await expect(summary.getByRole('button', { name: 'Modifier ma voiture', exact: true })).toBeFocused()
    await expect(panel.getByLabel('Places passagers proposées')).toHaveCount(0)
    await summary.getByRole('button', { name: 'Retirer ma voiture', exact: true }).click()
    await panel.getByRole('button', { name: 'Conserver ma voiture', exact: true }).click()
    await expect(summary).toBeVisible()
    await summary.getByRole('button', { name: 'Retirer ma voiture', exact: true }).click()
    await panel.getByRole('button', { name: 'Confirmer le retrait de ma voiture', exact: true }).click()
    await expect(summary).toHaveCount(0)
    for (const passenger of passengers) {
      const result = await organizer.from('session_participations').select('rsvp').eq('session_id', id).eq('member_id', passenger.memberId).single()
      expect(result.data?.rsvp).toBe('yes')
    }
    await page.getByRole('button', { name: 'Mon profil', exact: true }).click()
    await expect(usual.getByLabel('Places passagers habituelles')).toHaveValue('2')
    await expect(usual.getByLabel('Point de rendez-vous habituel')).toHaveValue('Parking habituel')
  } finally {
    if (id) await organizer.rpc('delete_session', { p_session_id: id })
    for (const passenger of passengers) await removeMemberFixture(passenger)
    await removeMemberFixture(driver); await removeMemberFixture(admin)
  }
})
